### ISSUE TITLE
Avoid second restart of Docker daemon after package upgrades

### ISSUE THREAD

**Issue by berendt** [osism/issues#1010]
A package upgrade of Docker (e.g. from 20.10 to 24.09) already restarts the Docker daemon. A second restart at the end via handler is then not necessary and can be avoided.

**Comment by berendt** [comment]
Current state is just fine. We do not trigger a restart with the package upgrade itself.

```
- name: Install docker package
  become: true
  ansible.builtin.apt:
    name: "{{ docker_package_name }}={{ docker_version }}*"
    state: present
    lock_timeout: "{{ apt_lock_timeout | default(300) }}"
    allow_downgrade: true
```
