### ISSUE TITLE
openstack-exporter still <nil> values in nova_server_status

### ISSUE THREAD

**Issue by mario-minners** [osism/issues#1018]
Hi,

The openstack exporter container is started with "OS_COMPUTE_API_VERSION=latest", this is not allowed.

❯ OS_COMPUTE_API_VERSION=latest openstack server list
Invalid format of client version 'latest'. Expected format 'X.Y', where X is a major part and Y is a minor part of version.

This breaks the fixes rolled out with Version 1.7

Ref: https://github.com/openstack-exporter/openstack-exporter/pull/308

**Comment by mario-minners** [comment]
This should work instead.

❯ OS_COMPUTE_API_VERSION=2.latest openstack server list -vvv 2>&1 | grep "API version"
compute API version 2.latest, cmd group openstack.compute.v2
identity API version 3, cmd group openstack.identity.v3
image API version 2, cmd group openstack.image.v2
network API version 2, cmd group openstack.network.v2
object_store API version 1, cmd group openstack.object_store.v1
volume API version 3, cmd group openstack.volume.v3
dns API version 2, cmd group openstack.dns.v2
neutronclient API version 2, cmd group openstack.neutronclient.v2
load_balancer API version 2.0, cmd group openstack.load_balancer.v2
orchestration API version 1, cmd group openstack.orchestration.v1

**Comment by berendt** [comment]
```
dragon@testbed-manager:~$ docker inspect prometheus_openstack_exporter | grep OS_COMPUTE_API_VERSION
                "OS_COMPUTE_API_VERSION=latest",
```

Defaults in kolla-ansible:

```
  prometheus-openstack-exporter:
    container_name: "prometheus_openstack_exporter"
    group: "prometheus-openstack-exporter"
    enabled: "{{ enable_prometheus_openstack_exporter | bool }}"
    environment:
      OS_COMPUTE_API_VERSION: "{{ prometheus_openstack_exporter_compute_api_version }}"
    image: "{{ prometheus_openstack_exporter_image_full }}"
    volumes: "{{ prometheus_openstack_exporter_default_volumes + prometheus_openstack_exporter_extra_volumes }}"
    dimensions: "{{ prometheus_openstack_exporter_dimensions }}"
    haproxy:
      prometheus_openstack_exporter:
        enabled: "{{ enable_prometheus_openstack_exporter | bool }}"
        mode: "http"
        external: false
        port: "{{ prometheus_openstack_exporter_port }}"
        backend_http_extra:
          - "timeout server {{ prometheus_openstack_exporter_timeout }}"
      prometheus_openstack_exporter_external:
        enabled: "{{ enable_prometheus_openstack_exporter_external | bool }}"
        mode: "http"
        external: true
        port: "{{ prometheus_openstack_exporter_port }}"
        backend_http_extra:
          - "timeout server {{ prometheus_openstack_exporter_timeout }}"
```

Workaround:

Set ``prometheus_openstack_exporter_compute_api_version`` in ``environments/kolla/configuration.yml`` to set a good version. I will prepare a fix for the wrong default on Friday.
