### ISSUE TITLE
[bug] Faulty template file for Nexus

### ISSUE THREAD

**Issue by rmueller-b1** [osism/issues#1057]
### OSISM release version

Some older version

### What's the problem?

In the template file for the docker-compose.yml of the Nexus is a doubled entry that causes the docker-compose@nexus.service to crash. The template file is located in the osism-ansible container at `collections/ansible_collections/osism/services/roles/nexus/templates/docker-compose.yml.j2`.

The faulty part is:
```
    22      volumes:
    23        - "/etc/hosts:/etc/hosts:ro"
    24      healthcheck:
    25        test: curl --silent --fail localhost:8081/nexus/
    26      volumes:
    27        - "data:/nexus-data"
    28        - "{{ nexus_configuration_directory }}/nexus.properties:/nexus-data/etc/nexus.properties:ro"
```
The doubled volumes in lines 22 and 26 is causing the issue.

Our used OSISM version is 4.3.0

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low

**Comment by osfrickler** [comment]
The issue has been fixed with https://github.com/osism/ansible-collection-services/pull/1238 already, please use a recent, supported version of OSISM.

**Comment by berendt** [comment]
As workaround you can edit the template in the running osism-ansible container at `/ansible/collections/ansible_collections/osism/services/roles/nexus/templates/docker-compose.yml.j2`:

```
[...]
    healthcheck:
      test: curl --silent --fail localhost:8081
    volumes:
      - "/etc/hosts:/etc/hosts:ro"
      - "data:/nexus-data"
      - "logback:/nexus-data/etc/logback"
      - "{{ nexus_configuration_directory }}/nexus.properties:/nexus-data/etc/nexus.properties:ro"
[...]
```
