### ISSUE TITLE
[bug]  don't use string comparison when comparing ip addresses

### ISSUE THREAD

**Issue by artificial-intelligence** [osism/issues#1095]
### OSISM release version

latest

### What's the problem?

in https://github.com/osism/defaults/blob/6cdeb577e61aeddabdca5faa2add6406bc26eb6e/all/001-kolla-defaults.yml#L59 we use the jinja `==` operator which only tests if some objects are equal objects, in our case strings. This can be problematic when applied to IPs, take this test playbook, which illustrates the problem:

```yaml problematic_ip_comparison.yml
---
- name: Test IP Address Comparison
  hosts: localhost
  gather_facts: no
  vars:
    kolla_external_vip_address: "192.168.1.1"
    kolla_internal_vip_address: "192.168.001.001"

  tasks:
    - name: Compare IP addresses as strings
      set_fact:
        string_comparison_result: "{{ kolla_external_vip_address == kolla_internal_vip_address }}"

    - name: Compare IP addresses using ipaddr filter
      set_fact:
        ipaddr_comparison_result: "{{ kolla_external_vip_address | ansible.utils.ipaddr('address') == kolla_internal_vip_address | ansible.utils.ipaddr('address') }}"

    - name: Display string comparison result
      debug:
        msg: "String comparison result: {{ string_comparison_result }}"

    - name: Display ipaddr filter comparison result
      debug:
        msg: "IP address comparison result: {{ ipaddr_comparison_result }}"
```

Output:

```
ansible-playbook problematic_ip_comparison.yml                      ✔  at 16:59:43 
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [Test IP Address Comparison] ****************************************************************************************

TASK [Compare IP addresses as strings] ***********************************************************************************
ok: [localhost]

TASK [Compare IP addresses using ipaddr filter] **************************************************************************
ok: [localhost]

TASK [Display string comparison result] **********************************************************************************
ok: [localhost] => 
  msg: 'String comparison result: False'

TASK [Display ipaddr filter comparison result] ***************************************************************************
ok: [localhost] => 
  msg: 'IP address comparison result: True'

PLAY RECAP ***************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0  
```

I'll provide a patch to use `ansible.utils.ipaddr()` instead.

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low
