### ISSUE TITLE
[bug] ceph-pools don't generate new keys

### ISSUE THREAD

**Issue by zachelnet** [osism/issues#1096]
### OSISM release version

7.1.0

### What's the problem?

Detailed description of the problem

we added client.manila under openstack_keys to create new key for the service:

```
openstack_keys:
....
  - name: client.manila
    caps:
      mon: "allow r"
      mgr: "allow rw"
      osd: "allow rw pool={{ cephfs_data_pool.name }}"
    mode: "0600"
```

With ceph-ansible:7.1.0 the key won't be created when we run the command `osism apply ceph-pools', but with ceph-ansible:6.0.2 it works.

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low
