### ISSUE TITLE
[bug] CIAB does not deploy successfully - netplan errror in network definition: unknown key 'dummy-devices

### ISSUE THREAD

**Issue by scoopex** [osism/issues#1103]
### OSISM release version

7.1.2

### What's the problem?

According to /var/log/install-cloud-in-a-box.log the deployment fails because of a a not accepted entry in the netplan configuration.
Image downloaded from from https://swift.services.a.regiocloud.tech/swift/v1/AUTH_b182637428444b9aa302bb8d5a5a418c/osism-node-image/ubuntu-autoinstall-cloud-in-a-box-2.iso with checksum 
498aa4ee3bc15e11bac885f311dde433ffb22a9aace3988c4b2b30666bad51c7.

```
root@osism-ae0461:/home/osism# netplan apply
/etc/netplan/01-osism.yaml:16:3: Error in network definition: unknown key 'dummy-devices'
  dummy-devices:


root@osism-ae0461:/home/osism# cat /etc/netplan/01-osism.yaml 
# This file describes the network interfaces available on your system
# For more information, see netplan(5).
---
network:
  version: 2
  renderer: networkd

  bonds:
    {}


  bridges:
    {}


  dummy-devices:
    {}


  ethernets:
    eno1np0:
        dhcp4: true


  tunnels:
    {}


  vlans:
    vlan100:
        addresses:
        - 192.168.16.10/24
        id: 100
        link: eno1np0
    vlan101:
        id: 101
        link: eno1np0


  vrfs:
    {}
```

According to the manpage on the system, "dummy-devices" is not a valid toplevel key.

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low
