### ISSUE TITLE
ceph-configure-lvm-volumes: write generated config back to netbox

### ISSUE THREAD

**Issue by fzakfeld** [osism/issues#1113]
`ceph-configure-lvm-volumes` will generate a config for the individual hosts that needs to be copied manually to host_vars. Since we use netbox with config context for host-specific configuration, I think it would be good if that could be done automatically from that playbook.

I can contribute this, just want to get the idea in first.

**Comment by jklare** [comment]
Hi @fzakfeld , I just stumbled over this issue and was wondering if there have been any further thoughts or maybe even an implementation on your side? Personally, i think using the netbox to store this information might overload it at some point. I assume the idea here would be to generate this configuration and save it in the netbox git repository, instead of the normal config repository (as created with cfg-cookiecutter)? Pushing it into the already running netbox would probably interfere with the netbox contents being generated from the netbox repository by introducing a second source of truth.

**Comment by fzakfeld** [comment]
Hey @jklare, I still think this would be a very useful feature and that the data should be in netbox, rather than the config repo. We are in the process of setting up a new env right now, and will probably implement this in some way here. Once it works, I'll try to upstream it

**Comment by fzakfeld** [comment]
Like already mentioned by @jklare, writing this into the device's local config context is not a good idea, as it overrides the defined context from the netbox repo (and vice versa).

The initial config looks like this and can be defined by using config context:
```
ceph_osd_devices:
  nvme0n1:
  nvme0n2:
```

This should already be available in the inventory if set. `ceph-configure-lvm-volumes` will generate something like this
```
ceph_osd_devices:
  nvme0n1:
    osd_lvm_uuid: 196aad32-7cc4-5350-8a45-1b03f50fc9bb
  nvme0n2:
    osd_lvm_uuid: c6df96be-1264-5815-9cb2-da5eb453a6de
lvm_volumes:
- data: osd-block-196aad32-7cc4-5350-8a45-1b03f50fc9bb
  data_vg: ceph-196aad32-7cc4-5350-8a45-1b03f50fc9bb
- data: osd-block-c6df96be-1264-5815-9cb2-da5eb453a6de
  data_vg: ceph-c6df96be-1264-5815-9cb2-da5eb453a6de
```
The in-band manager would need to pick up this config (stored in a temp file) and sync it into a custom field. The inventory reconciler would need to prefer the custom field over the config context if set.

Custom field: `ceph_devices`
Sync command: `osism sync ceph-devices`

@berendt if you are fine with this design we will go ahead and implement this
