### ISSUE TITLE
designate: non-destructive DNS pools update not working after Upgrade to OSISM 7.1.3

### ISSUE THREAD

**Issue by chrisschwa** [osism/issues#1157]
# OSISM release version
7.1.3

# Problem
```
TASK [designate : Non-destructive DNS pools update] ****************************
fatal: [control01]: FAILED! => {"changed": true, "cmd": ["docker", "exec", "-t", "designate_worker", "designate-manage", "pool", "update"], "delta": "0:01:02.472904", "end": "2024-10-04 13:49:11.535922", "msg": "non-zero return code", "rc": 1, "start": "2024-10-04 13:48:09.063018", "stderr": "", "stderr_lines": [], "stdout": "\r\nUpdating Pools Configuration\r\n****************************", "stdout_lines": ["", "Updating Pools Configuration", "****************************"]}
```

# Original Problem (which is solved but with no resolution)
_Originally posted by @chrisschwa in https://github.com/osism/issues/issues/1122#issuecomment-2393765164_

**Comment by berendt** [comment]
Please always specify the version from which the upgrade was done.

**Comment by berendt** [comment]
That's the command that is not working:

```
docker exec -t designate_worker designate-manage pool update
```

**Comment by berendt** [comment]
Please run `docker exec -t designate_worker designate-manage pool update --dry-run` on one of the Designate nodes and paste the output.

**Comment by berendt** [comment]
Contents of `/etc/kolla/designate-worker/pools.yaml`?

**Comment by chrisschwa** [comment]
```

cat /etc/kolla/designate-worker/pools.yaml
- name: default
  id: 55992ab9-8434-4fe0-ba11-638882de6f2d
  description: pdns pool primary
  attributes: {}
  ns_records:
    - hostname: ns1.cloud.cnds.io.
      priority: 1
    - hostname: ns2.cloud.cnds.io.
      priority: 1
    - hostname: ns3.cloud.cnds.io.
      priority: 1
  nameservers:
    - host: 168.119.237.242
      port: 53
    - host: 128.140.127.238
      port: 53
    - host: 65.109.169.249
      port: 53
  targets:
    - type: pdns4
      description: PDNS4 Server 168.119.237.242
      masters:
        - host: 62.67.3.100
          port: 5352
        - host: 62.67.3.100
          port: 5353
        - host: 62.67.3.100
          port: 5354
      options:
        host: 168.119.237.242
        port: 53
        api_endpoint: _redacted_
        api_token: _redacted_
    - type: pdns4
      description: PDNS4 Server 128.140.127.238
      masters:
        - host: 62.67.3.100
          port: 5352
        - host: 62.67.3.100
          port: 5353
        - host: 62.67.3.100
          port: 5354
      options:
        host: 128.140.127.238
        port: 53
        api_endpoint: _redacted_
        api_token: _redacted_
    - type: pdns4
      description: PDNS4 Server 65.109.169.249
      masters:
        - host: 62.67.3.100
          port: 5352
        - host: 62.67.3.100
          port: 5353
        - host: 62.67.3.100
          port: 5354
      options:
        host: 65.109.169.249
        port: 53
        api_endpoint: _redacted_
        api_token: _redacted_
```
