### ISSUE TITLE
Feature Request: add debops.ansible to osism apply

### ISSUE THREAD

**Issue by zachelnet** [osism/issues#1189]
Hi,

It's possible to run debops.ansible directly from osism apply, because I wanted to use depops.ansible tools.

Best Regards
Martin

**Comment by berendt** [comment]
For the time being you can use any Debops role this way:

Create a new custom play in `environments/custom/playbook-debops.yml` and run it with `osism apply -e custom debops -- -e debops_role_name=ansible`.

```yaml
# https://docs.debops.org/en/latest/ansible/role-index.html
---
- hosts: "{{ hosts_debops | default('generic') }}"
  tasks:
    - name: Include debops role
      ansible.builtin.include_role:
        name: "debops.debops.{{ debops_role_name | default('sysfs') }}"
```
