### ISSUE TITLE
[bug] deployment with manager_version: 9.0.0 fails

### ISSUE THREAD

**Issue by scpcom** [osism/issues#1269]
### OSISM release version

9.0.0

### What's the problem?

Deployment with "manager_version: 9.0.0" fails very early with: "manifest for quay.io/osism/osism-ansible:9.0.0 not found: manifest unknown"

```
PLAY [Apply role manager] **********************************************************************************************

........

TASK [osism.services.manager : Pull container images] ******************************************************************
fatal: [node01]: FAILED! => {"actions": [{"id": "inventory_reconciler", "status": "Pulling", "what": "image"}, {"id": "osism-ansible", "status": "Pulling", "what": "image"}, {"id": "flower", "status": "Pulling", "what": "image"}, {"id": "redis", "status": "Pulling", "what": "image"}, {"id": "ara-server", "status": "Pulling", "what": "image"}, {"id": "ceph-ansible", "status": "Pulling", "what": "image"}, {"id": "netbox", "status": "Pulling", "what": "image"}, {"id": "osism-kubernetes", "status": "Pulling", "what": "image"}, {"id": "kolla-ansible", "status": "Pulling", "what": "image"}, {"id": "mariadb", "status": "Pulling", "what": "image"}], "changed": false, "cmd": "/usr/bin/docker compose --ansi never --progress json --project-directory /opt/manager pull --", "msg": "Error when processing osism-ansible: manifest for quay.io/osism/osism-ansible:9.0.0 not found: manifest unknown: manifest unknown\nGeneral error: Error response from daemon: manifest for quay.io/osism/osism-ansible:9.0.0 not found: manifest unknown: manifest unknown", "rc": 1, "stderr": "{\"id\":\"openstack\",\"text\":\"Skipped - Image is already being pulled by flower\"}\n{\"id\":\"inventory_reconciler\",\"text\":\"Pulling\"}\n{\"id\":\"beat\",\"text\":\"Skipped - Image is already being pulled by flower\"}\n{\"id\":\"watchdog\",\"text\":\"Skipped - Image is already being pulled by flower\"}\n{\"id\":\"api\",\"text\":\"Skipped - Image is already being pulled by flower\"}\n{\"id\":\"osismclient\",\"text\":\"Skipped - Image is already being pulled by flower\"}\n{\"id\":\"conductor\",\"text\":\"Skipped - Image is already being pulled by flower\"}\n{\"id\":\"osism-ansible\",\"text\":\"Pulling\"}\n{\"id\":\"flower\",\"text\":\"Pulling\"}\n{\"id\":\"redis\",\"text\":\"Pulling\"}\n{\"id\":\"ara-server\",\"text\":\"Pulling\"}\n{\"id\":\"ceph-ansible\",\"text\":\"Pulling\"}\n{\"id\":\"netbox\",\"text\":\"Pulling\"}\n{\"id\":\"osism-kubernetes\",\"text\":\"Pulling\"}\n{\"id\":\"kolla-ansible\",\"text\":\"Pulling\"}\n{\"id\":\"mariadb\",\"text\":\"Pulling\"}\n{\"id\":\"mariadb\",\"text\":\"Pulled\"}\n{\"id\":\"redis\",\"text\":\"Pulled\"}\n{\"id\":\"netbox\",\"text\":\"Pulled\"}\n{\"id\":\"flower\",\"text\":\"Pulled\"}\n{\"id\":\"ara-server\",\"text\":\"Pulled\"}\n{\"id\":\"inventory_reconciler\",\"text\":\"Pulled\"}\n{\"id\":\"osism-ansible\",\"text\":\"Error\",\"status\":\"manifest for quay.io/osism/osism-ansible:9.0.0 not found: manifest unknown: manifest unknown\"}\n{\"id\":\"ceph-ansible\",\"status\":\"Interrupted\"}\n{\"id\":\"osism-kubernetes\",\"status\":\"Interrupted\"}\n{\"id\":\"kolla-ansible\",\"status\":\"Interrupted\"}\n{\"error\":true,\"message\":\"Error response from daemon: manifest for quay.io/osism/osism-ansible:9.0.0 not found: manifest unknown: manifest unknown\"}\n", "stderr_lines": ["{\"id\":\"openstack\",\"text\":\"Skipped - Image is already being pulled by flower\"}", "{\"id\":\"inventory_reconciler\",\"text\":\"Pulling\"}", "{\"id\":\"beat\",\"text\":\"Skipped - Image is already being pulled by flower\"}", "{\"id\":\"watchdog\",\"text\":\"Skipped - Image is already being pulled by flower\"}", "{\"id\":\"api\",\"text\":\"Skipped - Image is already being pulled by flower\"}", "{\"id\":\"osismclient\",\"text\":\"Skipped - Image is already being pulled by flower\"}", "{\"id\":\"conductor\",\"text\":\"Skipped - Image is already being pulled by flower\"}", "{\"id\":\"osism-ansible\",\"text\":\"Pulling\"}", "{\"id\":\"flower\",\"text\":\"Pulling\"}", "{\"id\":\"redis\",\"text\":\"Pulling\"}", "{\"id\":\"ara-server\",\"text\":\"Pulling\"}", "{\"id\":\"ceph-ansible\",\"text\":\"Pulling\"}", "{\"id\":\"netbox\",\"text\":\"Pulling\"}", "{\"id\":\"osism-kubernetes\",\"text\":\"Pulling\"}", "{\"id\":\"kolla-ansible\",\"text\":\"Pulling\"}", "{\"id\":\"mariadb\",\"text\":\"Pulling\"}", "{\"id\":\"mariadb\",\"text\":\"Pulled\"}", "{\"id\":\"redis\",\"text\":\"Pulled\"}", "{\"id\":\"netbox\",\"text\":\"Pulled\"}", "{\"id\":\"flower\",\"text\":\"Pulled\"}", "{\"id\":\"ara-server\",\"text\":\"Pulled\"}", "{\"id\":\"inventory_reconciler\",\"text\":\"Pulled\"}", "{\"id\":\"osism-ansible\",\"text\":\"Error\",\"status\":\"manifest for quay.io/osism/osism-ansible:9.0.0 not found: manifest unknown: manifest unknown\"}", "{\"id\":\"ceph-ansible\",\"status\":\"Interrupted\"}", "{\"id\":\"osism-kubernetes\",\"status\":\"Interrupted\"}", "{\"id\":\"kolla-ansible\",\"status\":\"Interrupted\"}", "{\"error\":true,\"message\":\"Error response from daemon: manifest for quay.io/osism/osism-ansible:9.0.0 not found: manifest unknown: manifest unknown\"}"], "stdout": "", "stdout_lines": []}

PLAY RECAP *************************************************************************************************************
node01                     : ok=34   changed=0    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   

```

### References to existing reports

References to existing bug reports, mailing lists, ...

### Severity

low

### Urgency

low

**Comment by berendt** [comment]
Please read the release notes and use 9.1.0.

https://osism.tech/docs/release-notes/osism-9#new-container-registry

**Comment by scpcom** [comment]
Thank you for the hint. I will add the container registry parameters before starting the next deployment with 9.1.0.

**Comment by scpcom** [comment]
I am sorry , I would re-open this. I did switch to "manager_version: 9.1.0" and added/changed the docker namespace and registry entries.
Now I get "Error response from daemon: unknown: artifact osism/kolla-ansible:9.1.0 not found" at the same step.

```
PLAY [Apply role manager] **********************************************************************************************************************************************************
...
ASK [osism.services.manager : Pull container images] ******************************************************************************************************************************
fatal: [node01]: FAILED! => {"actions": [{"id": "osism-kubernetes", "status": "Pulling", "what": "image"}, {"id": "beat", "status": "Pulling", "what": "image"}, {"id": "kolla-ansible", "status": "Pulling", "what": "image"}, {"id": "redis", "status": "Pulling", "what": "image"}, {"id": "osism-ansible", "status": "Pulling", "what": "image"}, {"id": "ara-server", "status": "Pulling", "what": "image"}, {"id": "netbox", "status": "Pulling", "what": "image"}, {"id": "mariadb", "status": "Pulling", "what": "image"}, {"id": "ceph-ansible", "status": "Pulling", "what": "image"}, {"id": "inventory_reconciler", "status": "Pulling", "what": "image"}], "changed": false, "cmd": "/usr/bin/docker compose --ansi never --progress json --project-directory /opt/manager pull --", "msg": "Error when processing kolla-ansible: unknown: artifact osism/kolla-ansible:9.1.0 not found\nGeneral error: Error response from daemon: unknown: artifact osism/kolla-ansible:9.1.0 not found", "rc": 1, "stderr": "{\"id\":\"watchdog\",\"text\":\"Skipped - Image is already being pulled by beat\"}\n{\"id\":\"conductor\",\"text\":\"Skipped - Image is already being pulled by beat\"}\n{\"id\":\"osism-kubernetes\",\"text\":\"Pulling\"}\n{\"id\":\"beat\",\"text\":\"Pulling\"}\n{\"id\":\"openstack\",\"text\":\"Skipped - Image is already being pulled by beat\"}\n{\"id\":\"flower\",\"text\":\"Skipped - Image is already being pulled by beat\"}\n{\"id\":\"api\",\"text\":\"Skipped - Image is already being pulled by beat\"}\n{\"id\":\"osismclient\",\"text\":\"Skipped - Image is already being pulled by beat\"}\n{\"id\":\"kolla-ansible\",\"text\":\"Pulling\"}\n{\"id\":\"redis\",\"text\":\"Pulling\"}\n{\"id\":\"osism-ansible\",\"text\":\"Pulling\"}\n{\"id\":\"ara-server\",\"text\":\"Pulling\"}\n{\"id\":\"netbox\",\"text\":\"Pulling\"}\n{\"id\":\"mariadb\",\"text\":\"Pulling\"}\n{\"id\":\"ceph-ansible\",\"text\":\"Pulling\"}\n{\"id\":\"inventory_reconciler\",\"text\":\"Pulling\"}\n{\"id\":\"inventory_reconciler\",\"text\":\"Pulled\"}\n{\"id\":\"netbox\",\"text\":\"Pulled\"}\n{\"id\":\"kolla-ansible\",\"text\":\"Error\",\"status\":\"unknown: artifact osism/kolla-ansible:9.1.0 not found\"}\n{\"id\":\"osism-ansible\",\"status\":\"Interrupted\"}\n{\"id\":\"mariadb\",\"status\":\"Interrupted\"}\n{\"id\":\"redis\",\"status\":\"Interrupted\"}\n{\"id\":\"ara-server\",\"status\":\"Interrupted\"}\n{\"id\":\"osism-kubernetes\",\"status\":\"Interrupted\"}\n{\"id\":\"ceph-ansible\",\"status\":\"Interrupted\"}\n{\"error\":true,\"message\":\"Error response from daemon: unknown: artifact osism/kolla-ansible:9.1.0 not found\"}\n", "stderr_lines": ["{\"id\":\"watchdog\",\"text\":\"Skipped - Image is already being pulled by beat\"}", "{\"id\":\"conductor\",\"text\":\"Skipped - Image is already being pulled by beat\"}", "{\"id\":\"osism-kubernetes\",\"text\":\"Pulling\"}", "{\"id\":\"beat\",\"text\":\"Pulling\"}", "{\"id\":\"openstack\",\"text\":\"Skipped - Image is already being pulled by beat\"}", "{\"id\":\"flower\",\"text\":\"Skipped - Image is already being pulled by beat\"}", "{\"id\":\"api\",\"text\":\"Skipped - Image is already being pulled by beat\"}", "{\"id\":\"osismclient\",\"text\":\"Skipped - Image is already being pulled by beat\"}", "{\"id\":\"kolla-ansible\",\"text\":\"Pulling\"}", "{\"id\":\"redis\",\"text\":\"Pulling\"}", "{\"id\":\"osism-ansible\",\"text\":\"Pulling\"}", "{\"id\":\"ara-server\",\"text\":\"Pulling\"}", "{\"id\":\"netbox\",\"text\":\"Pulling\"}", "{\"id\":\"mariadb\",\"text\":\"Pulling\"}", "{\"id\":\"ceph-ansible\",\"text\":\"Pulling\"}", "{\"id\":\"inventory_reconciler\",\"text\":\"Pulling\"}", "{\"id\":\"inventory_reconciler\",\"text\":\"Pulled\"}", "{\"id\":\"netbox\",\"text\":\"Pulled\"}", "{\"id\":\"kolla-ansible\",\"text\":\"Error\",\"status\":\"unknown: artifact osism/kolla-ansible:9.1.0 not found\"}", "{\"id\":\"osism-ansible\",\"status\":\"Interrupted\"}", "{\"id\":\"mariadb\",\"status\":\"Interrupted\"}", "{\"id\":\"redis\",\"status\":\"Interrupted\"}", "{\"id\":\"ara-server\",\"status\":\"Interrupted\"}", "{\"id\":\"osism-kubernetes\",\"status\":\"Interrupted\"}", "{\"id\":\"ceph-ansible\",\"status\":\"Interrupted\"}", "{\"error\":true,\"message\":\"Error response from daemon: unknown: artifact osism/kolla-ansible:9.1.0 not found\"}"], "stdout": "", "stdout_lines": []}

PLAY RECAP *************************************************************************************************************************************************************************
node01                     : ok=34   changed=17   unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   

```

**Comment by berendt** [comment]
Please share your /opt/manager/docker-compose.yml file.

**Comment by scpcom** [comment]
```
---
services:

  ##########################################
  # inventory-reconciler service

  inventory_reconciler:
    restart: unless-stopped
    image: "registry.osism.tech/osism/inventory-reconciler:8.1.0"
    tmpfs:
      - /inventory.pre:uid=45000,gid=45000
    volumes:
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
      - "interface:/interface:ro"
      - "inventory_reconciler:/inventory"
      - "/opt/configuration:/opt/configuration:ro"
    healthcheck:
      test: pgrep celery
    environment:
      - CELERY=1
      - INVENTORY_FROM_NETBOX=False
    secrets:
      - NETBOX_TOKEN
    env_file:
      - "/opt/manager/configuration/netbox.env"

  ##########################################
  # ansible services (kolla-ansible, ..)

  osism-ansible: &ansible
    container_name: "osism-ansible"
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism-ansible:9.1.0"
    mem_limit: 64296m
    mem_reservation: 1024m
    cpus: "16"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    env_file:
      - "/opt/manager/configuration/ansible.env"
      - "/opt/manager/configuration/netbox.env"
      - "/opt/manager/configuration/ara.env"
    command: osism worker osism-ansible
    environment:
      - CELERY=1
    healthcheck:
      test: pgrep celery
    volumes:
      - "/etc/hosts:/etc/hosts:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "cache:/opt/ansible/cache"
      - "logs:/opt/ansible/logs"
      - "share:/share"
      - "/opt/archive:/archive:rw"
      - "/opt/configuration:/opt/configuration:ro"
      - "/opt/state/netbox:/state:ro"
      - "/opt/ansible/secrets:/ansible/secrets:ro"
      - "inventory_reconciler:/ansible/inventory:ro"
      - "interface:/interface"
    secrets:
      - NETBOX_TOKEN
    depends_on:
      inventory_reconciler:
        condition: service_started
      redis:
        condition: service_healthy
      ara-server:
        condition: service_started

  osism-kubernetes:
    <<: *ansible
    container_name: "osism-kubernetes"
    image: "registry.osism.tech/osism/osism-kubernetes:9.1.0"
    mem_limit: 64296m
    mem_reservation: 1024m
    cpus: "16"
    command: osism worker osism-kubernetes
    healthcheck:
      test: pgrep celery
    environment:
      - CELERY=1
  ceph-ansible:
    <<: *ansible
    container_name: "ceph-ansible"
    image: "registry.osism.tech/osism/ceph-ansible:9.1.0"
    mem_limit: 64296m
    mem_reservation: 1024m
    cpus: "16"
    command: osism worker ceph-ansible
    healthcheck:
      test: pgrep celery
    environment:
      - CELERY=1
  kolla-ansible:
    <<: *ansible
    container_name: "kolla-ansible"
    image: "registry.osism.tech/osism/kolla-ansible:9.1.0"
    mem_limit: 64296m
    mem_reservation: 1024m
    cpus: "16"
    command: osism worker kolla-ansible
    healthcheck:
      test: pgrep celery
    environment:
      - CELERY=1

  ##########################################
  # Netbox

  netbox:
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism-netbox:0.20241219.2"
    command: osism worker netbox
    volumes:
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
      - "/opt/configuration/netbox:/netbox:ro"
      - "/opt/state/netbox:/state:rw"
      - "/opt/manager/configuration/conductor.yml:/etc/conductor.yml:ro"
    secrets:
      - NETBOX_TOKEN
    healthcheck:
      test: pgrep -f '/usr/local/bin/python3 /usr/local/bin/osism worker netbox'
    env_file:
      - "/opt/manager/configuration/netbox.env"
    deploy:
      replicas: 1

  ##########################################
  # services that necessarily require Celery


  ##########################################
  # conductor service for netbox integration

  conductor:
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism:0.20241219.2"
    command: osism worker conductor
    volumes:
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
      - "/opt/manager/configuration/conductor.yml:/etc/conductor.yml:ro"
      - "/opt/state/conductor:/state:rw"
    secrets:
      - NETBOX_TOKEN
    healthcheck:
      test: pgrep -f '/usr/local/bin/python3 /usr/local/bin/osism worker conductor'
    env_file:
      - "/opt/manager/configuration/conductor.env"
      - "/opt/manager/configuration/netbox.env"
      - "/opt/manager/configuration/openstack.env"


  ##########################################
  # openstack integration service

  openstack:
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism:0.20241219.2"
    command: osism worker openstack
    volumes:
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
      - "/opt/manager/configuration/conductor.yml:/etc/conductor.yml:ro"
      - "/opt/configuration/environments/openstack:/etc/openstack:ro"
    secrets:
      - NETBOX_TOKEN
    healthcheck:
      test: pgrep -f '/usr/local/bin/python3 /usr/local/bin/osism service openstack'
    env_file:
      - "/opt/manager/configuration/openstack.env"
      - "/opt/manager/configuration/netbox.env"

  ##########################################
  # watchdog service

  watchdog:
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism:0.20241219.2"
    command: osism service watchdog
    volumes:
      - "/opt/configuration:/opt/configuration:ro"
    healthcheck:
      test: pgrep -f '/usr/local/bin/python3 /usr/local/bin/osism service watchdog'

  ##########################################
  # api service

  api:
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism:0.20241219.2"
    command: osism service api
    ports:
      - "192.168.16.10:8000:8000"
    healthcheck:
      test: pgrep uvicorn
    secrets:
      - NETBOX_TOKEN
    env_file:
      - "/opt/manager/configuration/netbox.env"

  ##########################################
  # beat service

  beat:
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism:0.20241219.2"
    command: osism service beat
    healthcheck:
      test: pgrep celery
    secrets:
      - NETBOX_TOKEN
    env_file:
      - "/opt/manager/configuration/netbox.env"

  ##########################################
  # osismclient service

  osismclient:
    container_name: osismclient
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism:0.20241219.2"
    command: sleep infinity
    healthcheck:
      test: pgrep sleep
    secrets:
      - NETBOX_TOKEN
    env_file:
      - "/opt/manager/configuration/ansible.env"
      - "/opt/manager/configuration/client.env"
      - "/opt/manager/configuration/netbox.env"
      - "/opt/manager/configuration/ara.env"
    volumes:
      - "/etc/hosts:/etc/hosts:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "cache:/opt/ansible/cache"
      - "interface:/interface:ro"
      - "inventory_reconciler:/ansible/inventory:ro"
      - "share:/share"
      - "/opt/configuration:/opt/configuration:ro"
      - "/opt/ansible/secrets:/ansible/secrets:ro"
      - "/opt/manager/data:/data:ro"

  ##########################################
  # flower service

  flower:
    restart: unless-stopped
    image: "registry.osism.tech/osism/osism:0.20241219.2"
    command: osism service flower
    healthcheck:
      test: pgrep celery
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.flower-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.flower.entrypoints=http"
      - "traefik.http.routers.flower.rule=Host(`flower.services.scs-0000.acme.xyz`)"
      - "traefik.http.routers.flower.middlewares=flower-redirect-to-https@docker"
      - "traefik.http.routers.flower-secure.entrypoints=https"
      - "traefik.http.routers.flower-secure.tls=true"
      - "traefik.http.routers.flower-secure.rule=Host(`flower.services.scs-0000.acme.xyz`)"
      - "traefik.http.services.flower-secure.loadbalancer.server.port=5555"
    networks:
      - default
      - traefik

  ##########################################
  # redis service

  redis:
    restart: unless-stopped
    image: "index.docker.io/library/redis:7.4.1-alpine"
    command: redis-server --appendonly yes
    healthcheck:
      test: redis-cli ping
    networks:
      default:
        aliases:
          - cache

  ##########################################
  # ARA service

  ara-server:
    restart: unless-stopped
    image: "registry.osism.tech/osism/ara-server:1.7.2"
    env_file:
      - "/opt/manager/configuration/ara-server.env"
      - "/opt/manager/configuration/ara.env"
    volumes:
      - "/etc/hosts:/etc/hosts:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/state/ara-server:/state:rw"
    healthcheck:
      test: curl --silent --fail --basic --user $$ARA_API_USERNAME:$$ARA_API_PASSWORD http://localhost:8000
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.middlewares.ara-server-redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.ara-server-redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.ara-server.entrypoints=http"
      - "traefik.http.routers.ara-server.rule=Host(`ara.services.scs-0000.acme.xyz`)"
      - "traefik.http.routers.ara-server.middlewares=ara-server-redirect-to-https@docker"
      - "traefik.http.routers.ara-server-secure.entrypoints=https"
      - "traefik.http.routers.ara-server-secure.tls=true"
      - "traefik.http.services.ara-server-secure.loadbalancer.server.port=8000" 
      - "traefik.http.routers.ara-server-secure.rule=Host(`ara.services.scs-0000.acme.xyz`)"
    networks:
      - default
      - traefik
    depends_on:
      mariadb:
        condition: service_healthy

  ##########################################
  # mariadb service

  mariadb:
    restart: unless-stopped
    image: "index.docker.io/library/mariadb:11.6.2"
    env_file:
      - "/opt/manager/configuration/mariadb.env"
    volumes:
      - "mariadb:/var/lib/mysql"
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized --mariadbupgrade
      start_period: 30s


##########################################
# Volumes

volumes:
  inventory_reconciler:
  interface:
  cache:
  logs:
  mariadb:
  share:

##########################################
# Secrets

secrets:
  NETBOX_TOKEN:
    file: /opt/manager/secrets/NETBOX_TOKEN

##########################################
# Networks

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      driver: default
      config:
        - subnet:  172.31.101.0/27
  traefik:
    external: true

```
