### ISSUE TITLE
Integration of Manila with CephFS for Shared Filesystems in K8s

### ISSUE THREAD

**Issue by berendt** [osism/issues#142]

**Comment by Nils98Ar** [comment]
@matfechner Is there already a way to provide shared storage for a k8s rwx StorageClass in SCS somehow?

We would need this for shared storage between pod replicas.

**Comment by Nils98Ar** [comment]
Okay then we will wait until there is a recommended way!

**Comment by Nils98Ar** [comment]
Have you tested CephFS NFS-Ganesha with OSISM? Was there any outcome?

**Comment by berendt** [comment]
Mathias has left our company and has not continued with this task in the past. If there is a concrete need here, we would have to wait for the allocation of SCS VP03 so that we can include the topic of Manila and CephFS/NFS there in the near future.

**Comment by Nils98Ar** [comment]
Ok, thank you for the update.

I think it is quite important for K8s rwx volumes which are still needed sometimes.
Currently we are using nfs directly from K8s but Manila CSI integration would be better.

**Comment by berendt** [comment]
@fkr Please take up and prioritise. IMO after the major release.

**Comment by matfechner** [comment]
> Ok, thank you for the update.
> 
> I think it is quite important for K8s rwx volumes which are still needed sometimes. Currently we are using nfs directly from K8s but Manila CSI integration would be better.

@Nils98Ar there some open issues with the production grade of ganesha nfs itself, please have a look here: https://github.com/nfs-ganesha/nfs-ganesha/issues

**Comment by Nils98Ar** [comment]
Maybe I will try my luck with the ceph-nfs role and manila integration.
@berendt Where would you place the nfs containers? Control or storage nodes?

If I do not succeed we would wait for @fkr and SCS-VP03 ;)

**Comment by berendt** [comment]
On the storage nodes.

**Comment by Nils98Ar** [comment]
Could it be possible to use both CephFS and CephFS/NFS-Ganesha as manila backends at the same time?
E.g. allow CephFS only for own projects and CephFS/NFS-Ganesha for customer projects?

**Comment by Nils98Ar** [comment]
Manila with native cephfs is now working for us with manila-csi. We have created a private manila cephfs share type that is only accessible for selected projects.

Later we would create a public manila nfs-ganesha-cephfs share type.

**Comment by berendt** [comment]
@Nils98Ar Can you please share your steps?

**Comment by Nils98Ar** [comment]
OSISM-side or K8s or both?

**Comment by berendt** [comment]
I think it makes sense to have both.

**Comment by Nils98Ar** [comment]
**Deployment in OSISM (see https://github.com/osism/testbed/commit/008e9e7fb2ea8c41869965c1be8d1c74df8f0e37):**
- Ensure that network nodes (where the manila_share service is located per default) can reach `monitor_address` of control and storage nodes
- Add manila cephx user and place keyring in config repo if not already present, see https://github.com/osism/issues/issues/768#issuecomment-1822467022
- add config to `environments/kolla/configuration.yml`:
```
enable_manila: "yes"
enable_manila_backend_cephfs_native: "yes"
```
- add overlay file `ceph.conf` to `environments/kolla/files/overlays/manila`:
```
[global]
mon host = {% for host in groups['ceph-mon'] %}{{ hostvars[host]['monitor_address'] }}{% if not loop.last %},{% endif %}{% endfor %}

public network = {{ ceph_public_network }}
max open files = 131072
fsid = {{ ceph_cluster_fsid }}
```
 - `osism apply manila`
 - `osism apply loadbalancer`
 - `osism apply horizon` (and maybe `osism apply skyline`)

**Usage in OpenStack:**
 - Create private cephfs share type: 
```
openstack share type create --description "private cephfs share type for trusted projects" --extra-specs "share_backend_name=CEPHFS1" --public false  CephFS false
```
 - Grant access to share type for project:
```
openstack share type access create CephFS <project id>
```
 - Create share (protocol and type `CephFS`) + rule (type `cephx` and `access to` chosen freely) via horizon/cli etc.
 - Mount e.g. via kernel client (access to storage nodes and control nodes `monitor_address` needed, some warnings are expected, command is quite verbose): 
```
mount -t ceph -o 'name=<rule username/access to>,secret=<rule access key>' <share export location/path> <mount destination>
```
 - check success e.g. via `df -h`

**Deployment in K8s:**
 - install helm chart `ceph-csi-cephfs` from repo `https://ceph.github.io/csi-charts` in namespace `kube-system`
 - install helm chart `openstack-manila-csi` from repo `https://kubernetes.github.io/cloud-provider-openstack` in namespace `kube-system` with values:
```
fullNameOverride: "csi-manila-cephfs"
nameOverride: "csi-manila-cephfs"
shareProtocols:
  - protocolSelector: CEPHFS
    fsGroupPolicy: None
    fwdNodePluginEndpoint:
      dir: /var/lib/kubelet/plugins/cephfs.csi.ceph.com
      sockFile: csi.sock
```
 - Provide OpenStack application credentials for manila-csi in secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: csi-manila-secret
  namespace: kube-system
stringData:
  os-authURL: "<auth url>"
  os-region: "<region>"
  os-applicationCredentialID: "<credential id>"
  os-applicationCredentialSecret: "<credential secret>"
```
 - E.g. create secret csi-manila-secret from cloud-config secret (if application credential is used there):
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: csi-manila-secret
  namespace: kube-system
stringData:
  os-authURL: "$(kubectl get secret -n kube-system cloud-config -o json | jq -r '.data."cloud.conf"' | base64 -d | grep auth-url | cut -d"=" -f2 | tr -d "\"")"
  os-region: "$(kubectl get secret -n kube-system cloud-config -o json | jq -r '.data."cloud.conf"' | base64 -d | grep region | cut -d"=" -f2 | tr -d "\"")"
  os-applicationCredentialID: "$(kubectl get secret -n kube-system cloud-config -o json | jq -r '.data."cloud.conf"' | base64 -d | grep application-credential-id | cut -d"=" -f2 | tr -d "\"")"
  os-applicationCredentialSecret: "$(kubectl get secret -n kube-system cloud-config -o json | jq -r '.data."cloud.conf"' | base64 -d | grep application-credential-secret | cut -d"=" -f2 | tr -d "\"")"
EOF
```
 - Create StorageClass:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "manila-cephfs"
provisioner: "cephfs.manila.csi.openstack.org"
parameters:
  type: "CephFS" # name of manila share type
  csi.storage.k8s.io/provisioner-secret-name: csi-manila-secret # name of manila-csi secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system # namespace of manila-csi secret
  csi.storage.k8s.io/controller-expand-secret-name: csi-manila-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-manila-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/node-publish-secret-name: csi-manila-secret
  csi.storage.k8s.io/node-publish-secret-namespace: kube-system
```
**Usage in K8s:**
 - Create PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manila-cepfs-test
spec:
  storageClassName: manila-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
```
