### ISSUE TITLE
Discuss where to set the become argument of Ansible tasks and how to lint it

### ISSUE THREAD

**Issue by berendt** [osism/issues#171]
``become: true`` should always be set between ``name: `` and the actual task. This way you can see very quickly if a task needs extended rights or not.

```
- name: Copy motd file
  become: true
  ansible.builtin.copy:
    content: "{{ motd_content }}"
    dest: "{{ motd_path }}"
    owner: root
    group: root
    mode: 0644
```

Alternatively, we could set the ``become: true`` always as the last line. But I find it then quickly gets lost when ``loop`` or ``when`` is used.

No matter how we do it. It should be done uniformly and ensured via a linter.

Since it is not uniform in Kolla-Ansible at the moment, we should also discuss it there briefly and adjust it there as well.
