### ISSUE TITLE
ansible-lint: implement a syntax check for our become position

### ISSUE THREAD

**Issue by berendt** [osism/issues#178]
https://ansible-lint.readthedocs.io/en/latest/custom-rules/

**Comment by berendt** [comment]
```
- name: Copy hddtemp configuration file
  become: true
  ansible.builtin.copy:
    src: "{{ ansible_os_family }}/hddtemp"
    dest: "{{ hddtemp_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart hddtemp service
```
