### ISSUE TITLE
Cannot upgrade manager because docker compose service orch fails

### ISSUE THREAD

**Issue by linwalth** [osism/issues#221]
Running osism-upgrade-manager fails at 

`[osism.services.manager : Start/enable manager service]
`
when I check the logs I see the following error:

```
systemd[1]: Starting manager service managed by Docker Compose...
docker: 'compose' is not a docker command.
See 'docker --help'
docker-compose@manager.service: Control process exited, code=exited, status=1/FAILURE
docker-compose@manager.service: Failed with result 'exit-code'.
Failed to start manager service managed by Docker Compose.
```

It seems the operator user has no problem running sudo docker compose (I tested it impersonating the operator user)

~So it seems to me the playbook is just lacking a `become: true` for this task.~ 

See further rumination below...

**Comment by linwalth** [comment]
Did some further digging:

task path: /root/.ansible/collections/ansible_collections/osism/services/roles/manager/tasks/service.yml:18

=> 

```
- name: Start/enable manager service
  become: true
  ansible.builtin.service:
    name: "{{ manager_service_name }}"
    state: started
    enabled: true
```

It seems the service definition file lacks a sudo or the new docker compose command lacks accessibility by the operator.
