### ISSUE TITLE
Discussion: Do we really need noqa?

### ISSUE THREAD

**Issue by ra-beer** [osism/issues#334]
We have to discuss the using of the noqa's since some of them will be deprecated in the future. Currently only the noqa 301 and the noqa 503 are marked as outdated and caused warnings at the ansible-linter. For the moment we can change noqa 301 to noqa no-changed-when and noqa 503 to noqa no-handler. But we have to ask us: Is that the best practice? Shouldn´t we develop directly correct and use handlers and changed_when attributes? Nice to read your opinion.

**Comment by tibeer** [comment]
I would love to have the code reworked to reduce errors / warnings. Especially the no-changed-when is something we can definitely fix. But when it comes to no-handler, things get complicated (examples taken from https://github.com/ansible/ansible-lint/blob/f132d11f276a486ccc0c59f9aa6459b2942dfe1b/src/ansiblelint/rules/no_handler.md):

This is something ansible-lint will mark as wrong:
```yaml
---
- name: Example of no-handler rule
  hosts: localhost
  tasks:
    - name: Register result of a task
      ansible.builtin.copy:
        dest: "/tmp/placeholder"
        content: "Ansible made this!"
        mode: 0600
      register: result # <-- Registers the result of the task.
    - name: Second command to run
      ansible.builtin.debug:
        msg: The placeholder file was modified!
      when: result.changed # <-- Triggers the no-handler rule.
    - name: debugger
      ansible.builtin.debug:
        msg: "foobar!"
```

We use this approach, to run things directly. Handlers are handled after all tasks are completed.

Currently the execution order would be:
1. Register result of a task
2. Second command to run
3. debugger

If you now use the suggested solution from ansible-lint:

```yaml
---
- name: Example of no-handler rule
  hosts: localhost
  tasks:
    - name: Register result of a task
      ansible.builtin.copy:
        dest: "/tmp/placeholder"
        content: "Ansible made this!"
        mode: 0600
      notify:
        - Second command to run # <-- Handler runs only when the file changes.
    - name: debugger
      ansible.builtin.debug:
        msg: "foobar!"
  handlers:
    - name: Second command to run
      ansible.builtin.debug:
        msg: The placeholder file was modified!
```

the order changes:
1. Register result of a task
2. debugger
3. Second command to run

You can however overcome this by using meta:

```yaml
---
- name: Example of no-handler rule
  hosts: localhost
  tasks:
    - name: Register result of a task
      ansible.builtin.copy:
        dest: "/tmp/placeholder"
        content: "Ansible made this!"
        mode: 0600
      notify:
        - Second command to run # <-- Handler runs only when the file changes.
    - name: flush handlers
      meta: flush_handlers
    - name: debugger
      ansible.builtin.debug:
        msg: "foobar!"
  handlers:
    - name: Second command to run
      ansible.builtin.debug:
        msg: The placeholder file was modified!
```

The oder would now be:
1. Register result of a task
2. flush handlers
3. Second command to run
4. debugger

I innerly tend to like the "wrong" version more as it adds less complexity and most importantly, it reduces error sources. Reason being: If you use `flush_handlers` ALL handlers get triggered, that have received their notify already. This may cause for example a database to restart, even though it has not been fully configured through ansible leading to unwanted behaviour. Or am I mistaken here and there is an easy solution?
