### ISSUE TITLE
possibility to use different ceph cluster for separate az

### ISSUE THREAD

**Issue by chschilling** [osism/issues#343]
We want to run one ceph cluster for each az, but we are running into issues how to configure cinder correctly to serve all three backends in ha, as we have one controller per AZ.

we actually configure cinder to have three backends with separate AZ in the backend definition.
So one service per Controller can serve all three backends and provision volumes based on AZ.

```
[DEFAULT]
{% if ansible_fqdn in groups['cinder-volume'] %}
enabled_backends = {% for backend in ceph_enabled_az -%}rbd-{{ loop.index }}{% if not loop.last %},{% endif %}
{% endfor %}

{% for backend in ceph_enabled_az -%}
[rbd-{{ loop.index }}]
report_discard_supported = True
volume_backend_name = rbd-{{ backend }}
volume_driver = cinder.volume.drivers.rbd.RBDDriver
backend_host=rbd:{{ backend }}
backend_availability_zone={{ backend }}
# ceph.conf is not sufficient for multi backend az splitting, but we will have to wait for upstream to let us modify config.json
rbd_ceph_conf = /etc/ceph/ceph.conf
rbd_user = cinder
rbd_pool = volumes
rbd_secret_uuid = {{ cinder_rbd_secret_uuid }}
rbd_flatten_volume_from_snapshot = True
image_upload_use_cinder_backend = True
{% endfor %}

{% endif %}
```

Main issue in here is - we don't see a way to have three different ceph.conf files deployed to the same node.
We thought, best way to configure the backend would be to have : 
```
---
rbd_ceph_conf = /etc/ceph/ceph-{{  backend }}.conf
---
```

in the overlay, which would work, we can define one ceph conf per cluster, and, if we would have these three files roled out, it even would work with cinder volume and with cinder backup.
But kolla is searching for exact "ceph.conf" in the cinderfolder and the cinder container json is expecting ceph.conf as well and mounting the conf as ceph.conf inside the container.

There is already a blueprint, but noone cares so long

https://blueprints.launchpad.net/kolla-ansible/+spec/multiple-ceph-conf-files

Maybe this can be done via osism. or maybe  there is another way to configure this..

Greetings,

Christian

**Comment by berendt** [comment]
Upstream blueprint: https://blueprints.launchpad.net/kolla-ansible/+spec/multiple-ceph-conf-files

We'll get in contact with Juan if he is working on it. If not we'll take over. If yes we will try to help him with the implementation.

**Comment by linwalth** [comment]
Awesome!

**Comment by linwalth** [comment]
If there is any need, we have a raw untested solution for this matter. So if you need some starting point from where to expand, we can get in touch.

**Comment by berendt** [comment]
@linwalth Sure. Can you share the approach here in this issue?

**Comment by fkr** [comment]
@linwalth indeed this would be interesting for the community.

**Comment by linwalth** [comment]
The goal is to have cross-AZ HA for Cinder. (Thus, it is non-negotiable to set cross_az_attach = false for cinder volumes in nova) - Meaning: we wish to have connection data for all Ceph clusters in all AZs in cinder-backup and cinder-volume, so a cinder service dying does not kill off the service in the whole AZ.

The approach is to split up the ceph-service-configurations with the help of custom groups in 10-custom.yml, group_vars for these groups containing cluster connection data, and jinja2 templating kolla overlay files getting fed these vars differing from AZ to AZ - creating connection definition data for all 3 backends in the ceph-volume and ceph-backup files.

That is not enough to make it run, though, as there are no ceph-configs for these backups and the config.yaml for the container is still not using and allowing ceph configs for these multiple backends (remember, the goal is to create cross-AZ HA. Thus we created a somewhat raw and blunt playbook to override the config.yaml for the services and overwrite it with different config.yamls that make the container use the 3 different ceph-{{ az }}.confs and ceph-{{ az }}.client.cinder.keyrings.

(Small sidenote: Ceph Keyrings are being read out based on the client side cluster name defined by the ceph.conf: https://docs.ceph.com/en/latest/rados/operations/user-management/#keyring-management )

**Comment by linwalth** [comment]
@chschilling anything I forgot to add?

**Comment by chschilling** [comment]
That looks quite correct, could you add the playbook including custom json file, as that jsonfile part would be the most interessting thing, I think.

**Comment by linwalth** [comment]
````yaml
---
#this playbook is used to roll out custom ceph.conf files, config.json files, and cinder keyrings for cinder services to use multiple AZ backends for HA.
### !!! the configuration set by this PB is going to be overwritten by the Kolla Cinder Roles if you do not carefully utilize the --start-at-task parameter.
### !!! make sure to skip the config.yml task by choosing tasks after or around it. https://github.com/openstack/kolla-ansible/tree/stable/yoga/ansible/roles/cinder/tasks (meaning: if you want to upgrade, run the bootstrap role component by component, leaving out the config steps.)

- name: add config files for defined AZs to cinder-volume, then restart service
  hosts: cinder-volume
  gather_facts: true
  tasks:
    - name: Creating ceph-{{ item }}.conf for cinder-volume
      become: true
      template:
        src: "ceph.conf.j2"
        dest: "etc/kolla/cinder-volume/ceph-{{ item }}.conf"
        mode: "0660"
        loop: "{{ ceph_enabled_az }}"

    - name: Creating ceph-{{ ceph_enabled_az }}.client.cinder.keyring for cinder-volume
      become: true
      template:
        src: "ceph-keyring.j2"
        dest: "etc/kolla/cinder-volume/ceph-{{ item }}.client.cinder.keyring"
        mode: "0660"
        loop: "{{ ceph_enabled_az }}"

    - name: Copying over config.json files for cinder-volume
      become: true
      template:
        src: "config.json.j2"
        dest: "etc/kolla/cinder-volume/config.json"
        mode: "0660"

    - name: Remove ceph.client.cinder.keyring default for cinder-volume
      ansible.builtin.file:
        path: /etc/kolla/cinder-volume/ceph.client.cinder.keyring
        state: absent

    - name: Restarting cinder-volume service container
      become: true
      docker_container:
      name: cinder_volume
      state: started
      restart: yes


- name: add config files for defined AZs to cinder-backup, then restart service
  hosts: cinder-backup
  gather_facts: true
  tasks:
    - name: Creating ceph-{{ item }}.conf for cinder-backup
      become: true
      template:
        src: "ceph.conf.j2"
        dest: "etc/kolla/cinder-backup/ceph-{{ item }}.conf"
        mode: "0660"
        loop: "{{ ceph_enabled_az }}"

    - name: Creating ceph-{{ ceph_enabled_az }}.client.cinder.keyring for cinder-backup
      become: true
      template:
        src: "ceph-keyring.j2"
        dest: "etc/kolla/cinder-backup/ceph-{{ item }}.client.cinder.keyring"
        mode: "0660"
        loop: "{{ ceph_enabled_az }}"

    - name: Copying over config.json files for cinder-backup
      become: true
      template:
        src: "config.json.j2"
        dest: "etc/kolla/cinder-backup/config.json"
        mode: "0660"

    - name: Remove ceph.client.cinder.keyring default for cinder-backup
      ansible.builtin.file:
        path: /etc/kolla/cinder-backup/ceph.client.cinder.keyring
        state: absent

    - name: Remove ceph.client.cinder-backup.keyring default for cinder-backup
      ansible.builtin.file:
        path: /etc/kolla/cinder-backup/ceph.client.cinder-backup.keyring
        state: absent

    - name: Restarting cinder-backup service container
      become: true
      docker_container:
      name: cinder_backup
      state: started
      restart: yes
````

**Comment by linwalth** [comment]
**cinder-backup.json.j2**

````
{
    "command": "cinder-backup --config-file /etc/cinder/cinder.conf",
    "config_files": [
        {
            "source": "/var/lib/kolla/config_files/cinder.conf",
            "dest": "/etc/cinder/cinder.conf",
            "owner": "cinder",
            "perm": "0600"
        },
{% for backend in ceph_enabled_az -%}
        {
            "source": "/var/lib/kolla/config_files/ceph-{{ backend }}.conf",
            "dest": "/etc/ceph/ceph-{{ backend }}.conf",
            "owner": "cinder",
            "perm": "0600",
            "optional": false
        },
{% endfor %}
{% for backend in ceph_enabled_az -%}
        {
            "source": "/var/lib/kolla/config_files/ceph-{{ backend }}.client.cinder.keyring",
            "dest": "/etc/ceph/ceph-{{ backend }}.client.cinder.keyring",
            "owner": "cinder",
            "perm": "0600",
            "optional": false
        }{{ "," if not loop.last else "" }}
{% endfor %}
    ],
    "permissions": [
        {
            "path": "/var/lib/cinder",
            "owner": "cinder:cinder",
            "recurse": true
        },
        {
            "path": "/var/log/kolla/cinder",
            "owner": "cinder:cinder",
            "recurse": true
        }
    ]
}
````

**Comment by linwalth** [comment]
**cinder-volume.json.j2**

````
{
    "command": "cinder-volume --config-file /etc/cinder/cinder.conf",
    "config_files": [
        {
            "source": "/var/lib/kolla/config_files/cinder.conf",
            "dest": "/etc/cinder/cinder.conf",
            "owner": "cinder",
            "perm": "0600"
        },
{% for backend in ceph_enabled_az -%}
        {
            "source": "/var/lib/kolla/config_files/ceph-{{ backend }}.client.cinder.keyring",
            "dest": "/etc/ceph/ceph-{{ backend }}.client.cinder.keyring",
            "owner": "cinder",
            "perm": "0600",
            "optional": false
        },
{% endfor %}
{% for backend in ceph_enabled_az -%}
        {
            "source": "/var/lib/kolla/config_files/ceph-{{ backend }}.conf",
            "dest": "/etc/ceph/ceph-{{ backend }}.conf",
            "owner": "cinder",
            "perm": "0600",
            "optional": false
        },
{% endfor %}
        {
            "source": "/var/lib/kolla/config_files/nfs_shares",
            "dest": "/etc/cinder/nfs_shares",
            "owner": "cinder",
            "perm": "0600",
            "optional": true
        }
    ],
    "permissions": [
        {
            "path": "/var/lib/cinder",
            "owner": "cinder:cinder",
            "recurse": true
        },
        {
            "path": "/var/log/kolla/cinder",
            "owner": "cinder:cinder",
            "recurse": true
        }
    ]
}
````

**Comment by linwalth** [comment]
If there is any need for more configuration, I can anonymize and add that too.

**Comment by linwalth** [comment]
The playbook still lacked some refinement (I ran it today and fixed it where it did not work.)

the var for ceph_enabled_az has to go into environments/configuration.yml

```
---
#this playbook is used to roll out custom ceph.conf files, config.json files, and cinder keyrings for cinder services to use multiple AZ backends for HA.
### !!! the configuration set by this PB is going to be overwritten by the Kolla Cinder Roles if you do not carefully utilize the --start-at-task parameter.
### !!! make sure to skip the config.yml task by choosing Tasks after or around it. https://github.com/openstack/kolla-ansible/tree/stable/yoga/ansible/roles/cinder/tasks (meaning: if you want to upgrade, run the bootstrap role component by component, leaving out the config steps.)

- name: add config files for defined AZs to cinder-volume, then restart service
  hosts: cinder-volume
  gather_facts: true
  tasks:
    - name: "Creating ceph-{{ item }}.conf for cinder-volume"
      become: true
      template:
        src: "ceph.conf.j2"
        dest: "/etc/kolla/cinder-volume/ceph-{{ item }}.conf"
        mode: "0660"
      loop: "{{ ceph_enabled_az }}"

    - name: "Creating ceph-{{ ceph_enabled_az }}.client.cinder.keyring for cinder-volume"
      become: true
      template:
        src: "ceph-keyring.j2"
        dest: "/etc/kolla/cinder-volume/ceph-{{ item }}.client.cinder.keyring"
        mode: "0660"
      loop: "{{ ceph_enabled_az }}"

    - name: Copying over config.json files for cinder-volume
      become: true
      template:
        src: "cinder-volume.json.j2"
        dest: "/etc/kolla/cinder-volume/config.json"
        mode: "0660"

    - name: Remove ceph.client.cinder.keyring default for cinder-volume
      ansible.builtin.file:
        path: /etc/kolla/cinder-volume/ceph.client.cinder.keyring
        state: absent

    - name: Restarting cinder-volume service container
      become: true
      docker_container:
        name: cinder_volume
        state: started
        restart: yes


- name: add config files for defined AZs to cinder-backup, then restart service
  hosts: cinder-backup
  gather_facts: true
  tasks:
    - name: "Creating ceph-{{ item }}.conf for cinder-backup"
      become: true
      template:
        src: "ceph.conf.j2"
        dest: "/etc/kolla/cinder-backup/ceph-{{ item }}.conf"
        mode: "0660"
      loop: "{{ ceph_enabled_az }}"

    - name: "Creating ceph-{{ ceph_enabled_az }}.client.cinder.keyring for cinder-backup"
      become: true
      template:
        src: "ceph-keyring.j2"
        dest: "/etc/kolla/cinder-backup/ceph-{{ item }}.client.cinder.keyring"
        mode: "0660"
      loop: "{{ ceph_enabled_az }}"

    - name: Copying over config.json files for cinder-backup
      become: true
      template:
        src: "cinder-backup.json.j2"
        dest: "/etc/kolla/cinder-backup/config.json"
        mode: "0660"

    - name: Remove ceph.client.cinder.keyring default for cinder-backup
      ansible.builtin.file:
        path: /etc/kolla/cinder-backup/ceph.client.cinder.keyring
        state: absent

    - name: Remove ceph.client.cinder-backup.keyring default for cinder-backup
      ansible.builtin.file:
        path: /etc/kolla/cinder-backup/ceph.client.cinder-backup.keyring
        state: absent

    - name: Restarting cinder-backup service container
      become: true
      docker_container:
        name: cinder_backup
        state: started
        restart: yes

```
