### ISSUE TITLE
Add jammy to the list of supported platforms

### ISSUE THREAD

**Issue by berendt** [osism/issues#373]
jammy is not listed in meta/main.yml. Add jammy to the list for all roles in all collections.

```
  platforms:
    - name: Ubuntu
      versions:
        - focal
```
