### ISSUE TITLE
Find a way to document the defaults in the Ansible collections

### ISSUE THREAD

**Issue by berendt** [osism/issues#43]

**Comment by tibeer** [comment]
Ansible-collection-services? This might be done like UCS did it with their collection: https://galaxy.ansible.com/univention/ucs_roles

**Comment by berendt** [comment]
No, not like that. I would like to have if possible a standardized format which lives directly in the defaults definition. Like Python docstrings only for YAML/Ansible. The documents can then be generated from it.

**Comment by berendt** [comment]
I think it could make sense to adapt https://github.com/ansible/ansible/blob/devel/examples/DOCUMENTATION.yml for this use case. The ``options``part:

```
    option_name:
        description:
            - Description of the options goes here.
            - Must be written in sentences.
        required: true or false
        default: a string or the word null
        choices:
          - enable
          - disable
        aliases:
          - repo_name
        version_added: "1.X"
```
