### ISSUE TITLE
Remove all "Wait for apt lock" tasks

### ISSUE THREAD

**Issue by berendt** [osism/issues#464]
Not longer required after the fix of osism/issues#274.

```
- name: Wait for apt lock
  ansible.builtin.shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false
```
