### ISSUE TITLE
Regression (osism-v5.x): Booting from vda (virtio) breaks

### ISSUE THREAD

**Issue by garloff** [osism/issues#509]
On wavestack, booting from a volume that previously succeeded no longer works.
Booting the "Ubuntu Minimal 22.04" image to a flavor with local boot disk does no longer work either.
The noVNC console shows that it hangs in the BIOS, trying to load the bootloader from disk.
After spending half a day, the issue could be tracked to the image having set `hw_disk_bus=virtio` (vda).
Changing the image-property to `hw_disk_bus=scsi` (sda) makes it work again.
This is likely a regression in OSISM-5.x -- the VM in question had been running for a while before.

Sidenote: The [SCS image metadata standard](https://github.com/SovereignCloudStack/standards/blob/main/Drafts/Image-Properties-Spec.md) does recommend SCSI, as it tends to perform slightly better and supports DISCARD (fstrim). vda is common enough that we can probably not ignore this, though.

**Comment by berendt** [comment]
At least in the image manager we have the following definition (which should be fine):

https://github.com/osism/openstack-image-manager/blob/main/etc/images/ubuntu.yml#L247-L249

**Comment by berendt** [comment]
The following entry is included in the quay.io/osism/osism:0.20230407.0 image (this one is part of the 5.1.0 release). Looks good there as well.

```
  - name: Ubuntu 22.04 Minimal
    enable: true
    shortname: ubuntu-22.04-minimal
    format: qcow2
    login: ubuntu
    min_disk: 8
    min_ram: 512
    status: active
    visibility: public
    multi: true
    meta:
      architecture: x86_64
      hw_disk_bus: scsi
      hw_rng_model: virtio
      hw_scsi_model: virtio-scsi
      hw_watchdog_action: reset
      os_distro: ubuntu
      os_version: '22.04'
      replace_frequency: quarterly
      uuid_validity: last-3
      provided_until: none
    tags: []
    latest_checksum_url: https://cloud-images.ubuntu.com/minimal/releases/jammy/release/SHA256SUMS
    latest_url: https://cloud-images.ubuntu.com/minimal/releases/jammy/release/ubuntu-22.04-minimal-cloudimg-amd64.img
    versions:
      - version: '20230328'
        url: https://minio.services.osism.tech/openstack-image-manager/ubuntu-22.04-minimal/20230328-ubuntu-22.04-minimal.qcow2
        checksum: sha256:04dd2f3ed2ed76f4a3563cacada000bfe0409b959fd7e4dd5e72c80953c186c8
        build_date: '2023-03-28'
```
