### ISSUE TITLE
Create playbook to prepare Ceph OSD devices and reconfigure host vars automatically

### ISSUE THREAD

**Issue by ppkuschy** [osism/issues#595]
As an OSISM operator I want to be able to specify the devices which should be used for Ceph OSDs and then have a playbook available which automatically creates the LVM PVs, VGs and LVs according to that configuration and reconfigure the host_vars for a given host automatically. It should generate VGs with a naming scheme of ceph-<UUID> and LVs with naming scheme of osd-[block/db/wal]-<UUID> and automatically create a lvm_volumes config key for the host vars like in this example:
```
lvm_volumes:
  - data: osd-block-<UUID>
    data_vg: ceph-<UUID>
    db: osd-db-<UUID>
    db_vg: ceph-db-wal-<UUID>
    wal: osd-wal-<UUID>
    wal_vg: ceph-db-wal-<UUID>
```
This configuration can then be used by ceph-ansible to provision OSDs of a host.
The need for this playbook comes from the fact that specifying the `devices:` key for ceph-ansible isn't flexible enough, but when using `lvm_volumes:` instead of `devices:` the PVs, VGs and LVs all need to be already existing, as ceph-ansible won't create them automatically.
The configuration/inventory in the host vars for this playbook should look something like that:
```
ceph_osd_devices:
  - block_pv: /dev/sda
    wal_pv: /dev/nvme0n1
    db_pv: /dev/nvme0n1
    # Optional, when omitted will calculate size by counting the number of OSDs sharing a WAL or DB device, allocating 2 GiB for WAL
    # Will also optionally leave a buffer space of a configurable percentage (useful for better lifetime and performance of some SSDs)
    wal_size: <size-for-wal-lv>
    db_size: <size-for-db-lv>
# Optional, defaults to "false":
ceph_osd_devices_buffer_space_percent: 10
```
