### ISSUE TITLE
Check "Build container image" action in all container-image repositories

### ISSUE THREAD

**Issue by berendt** [osism/issues#60]
Container images should only be pushed in the ``Build container image`` action if the action is running on main in the upstream repository. No push should take place in forks.

Check all ``.github/workflows/build-container-image.yml`` files.  Job ``Push container image`` should have an if of the following form. The repository name must be adjusted accordingly depending on the repository.

```
      - name: Push container image
        run: |
          scripts/push.sh
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          REPOSITORY: osism/netbox
        if: |
          github.repository == 'osism/container-image-tang' &&
          github.ref == 'refs/heads/main'
```
