### ISSUE TITLE
Change the ``Wait for apt lock`` task in all roles in all Ansible collections

### ISSUE THREAD

**Issue by berendt** [osism/issues#61]
Change the ``Wait for apt lock`` task in all roles in all Ansible collections to:

```
- name: Wait for apt lock
  shell: "while fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1; do sleep 5; done;"
  loop:
    - lock
    - lock-frontend
  changed_when: false
```
