### ISSUE TITLE
Make it possible to use FQDN instead of shortname when bootstrapping

### ISSUE THREAD

**Issue by linwalth** [osism/issues#617]
Bootstrap only creates the hostname as shortname: 
https://github.com/osism/ansible-collection-commons/blob/main/roles/hostname/tasks/main.yml

We use FQDN for our nodes in the inventory.
It would be lovely if it was possible to use the FQDN provided from the inventory (something like this):

```
- name: hostname | set hostname FQDN
  hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
```

This would be configurable with a var like "hostname_use_fqdn: true/false"

Alternatively it would be sufficient for our usecase at least if we could have a variable to disable hostname provisioning, as we have our own mechanism for this.
