### ISSUE TITLE
The openstack-health-monitor role seems to be not functional and should be fixed

### ISSUE THREAD

**Issue by michaelbayr** [osism/issues#630]
The openstack-health-monitor role is automatically deployed in the testbed, yet it seems not functional. 

This is the currently generated configuration by the role:

```
osism@control01:~$ sudo cat /opt/openstack_health_monitor/configuration/openstack_health_monitor.env
ADDJHVOLSIZE=0
ADDVMVOLSIZE=0
AZS=nova
DATADIR=/data
FLAVOR=1C-1GB-5GB
IMG=Ubuntu 20.04
JHFLAVOR=1C-1GB-5GB
JHIMG=Ubuntu 20.04
OS_CLOUD=openstack_health_monitor
```

```
osism@control01:~$ sudo cat /opt/openstack_health_monitor/docker-compose.yml
---
services:
  openstack_health_monitor:
    container_name: "openstack_health_monitor"
    restart: unless-stopped
    image: "quay.io/sovereigncloudstack/openstack-health-monitor:v3.0.0"
    entrypoint: crond -f -c /configuration/crontabs
    env_file:
      - "/opt/openstack_health_monitor/configuration/openstack_health_monitor.env"
    volumes:
      - "/opt/openstack_health_monitor/configuration:/configuration:ro"
      - "/etc/hosts:/etc/hosts:ro"
      - "data:/data:rw"

volumes:
  data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      driver: default
      config:
        - subnet:  172.31.100.160/28
```

```
bash-5.1$ ls -lsah /configuration/crontabs/
total 8K     
     4 drwxr-x---    2 dragon   dragon      4.0K Jul  7 14:47 .
     4 drwxr-x---    3 dragon   dragon      4.0K Jul  7 14:47 ..

```

The `clouds.yaml` and `secure.yaml` are correctly in place.

## Problems
- There seems to be no crontab to actually start the script
- The flavors/images are not scs-compatible by default
- There is no influxdb/telegraf deployment in the testbed to push/pull to/from
- The OHM Grafana Dashboard is not added to grafana

## Expected behaviour
The deployed role should add all the necessary dependencies and create a working OHM that shows its metrics in the respective grafana dashboard.
