### ISSUE TITLE
Keystone with OIDC backend (keycloak)

### ISSUE THREAD

**Issue by killermoehre** [osism/issues#650]
Hi,

we deploy right now for a customer an environment.

I was able to configure a Keycloak as Keystone-Backend. Users are created in Keystone based on the ActiveDirectory behind the Keycloak on the first login in Horizon. But after that I only get the error message

```text
Error:

OpenID Connect Provider error: Error in handling response type.
```

`environments/kolla/configuration.yml`

```yaml
keycloak_url: "auth.redacted.de"
keycloak_realm: "redacted"
keystone_trusted_dashboards:
  - "https://{{ horizon_external_fqdn }}/auth/websso/"
keystone_public_url: "https://{{ kolla_external_fqdn }}:{{ keystone_public_port }}/v3"  # füge ausrücklich v3 an, damit der redirect sauber durch geht
enable_keystone_federation: "yes"
keystone_oidc_forward_header: "X-Forwarded-Proto"
keystone_enable_federation_openid: "yes"
keystone_federation_oidc_response_type: "code"
keystone_identity_providers:
  - name: "keycloak"
    openstack_domain: "{{ keycloak_realm }}"
    protocol: "openid"
    identifier: "https://{{ keycloak_url }}/realms/{{ keycloak_realm }}"
    public_name: "Anmeldung via AD Nutzer und AD Passwort"
    attribute_mapping: "mappingId1"
    metadata_folder: "{{ node_custom_config }}/keystone/metadata"
    certificate_file: "{{ node_custom_config }}/keystone/ix3bsRkD4JWr_7wj-rtl_DJZt1N1Q6QtLGj_yS8bmX4.pem"
keystone_identity_mappings:
  - name: "mappingId1"
    file: "{{ node_custom_config }}/keystone/oidc_attribute_mappingId1.json"
```

`environments/kolla/files/overlays/keystone/keystone.conf`

```ini
[DEFAULT]
debug = True

{% if enable_keystone_federation %}
[mapped]
remote_id_attribute = {{ keystone_remote_id_attribute_oidc }}
remove_dangling_assignments = True

[auth]
methods = password,token,openid,mapped,application_credential
{% endif %}
```

`environments/kolla/files/overlays/keystone/wsgi-keystone.conf` (I got this one form the OSISM testbed. I added, that the self-signed cert of the keycloak will be ignored.)

```jinja2
{% set keystone_log_dir = '/var/log/kolla/keystone' %}
{% set binary_path = '/var/lib/kolla/venv/bin' %}
{% if keystone_enable_tls_backend | bool %}
{% if kolla_base_distro in ['centos']  %}
LoadModule ssl_module /usr/lib64/httpd/modules/mod_ssl.so
{% else %}
LoadModule ssl_module /usr/lib/apache2/modules/mod_ssl.so
{% endif %}
{% endif %}
Listen {{ api_interface_address | put_address_in_context('url') }}:{{ keystone_public_listen_port }}
Listen {{ api_interface_address | put_address_in_context('url') }}:{{ keystone_admin_listen_port }}

ServerSignature Off
ServerTokens Prod
TraceEnable off
TimeOut {{ kolla_httpd_timeout }}
KeepAliveTimeout {{ kolla_httpd_keep_alive }}

ErrorLog "{{ keystone_log_dir }}/apache-error.log"
<IfModule log_config_module>
    CustomLog "{{ keystone_log_dir }}/apache-access.log" common
</IfModule>

{% if keystone_logging_debug | bool %}
LogLevel info
{% endif %}

<Directory "{{ binary_path }}">
    <FilesMatch "^keystone-wsgi-(public|admin)$">
        AllowOverride None
        Options None
        Require all granted
    </FilesMatch>
</Directory>


<VirtualHost *:{{ keystone_public_listen_port }}>
    WSGIDaemonProcess keystone-public processes={{ openstack_service_workers }} threads=1 user=keystone group=keystone display-name=keystone-public
    WSGIProcessGroup keystone-public
    WSGIScriptAlias / {{ binary_path }}/keystone-wsgi-public
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On
    <IfVersion >= 2.4>
      ErrorLogFormat "%{cu}t %M"
    </IfVersion>
    ErrorLog "{{ keystone_log_dir }}/keystone-apache-public-error.log"
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b %D \"%{Referer}i\" \"%{User-Agent}i\"" logformat
    CustomLog "{{ keystone_log_dir }}/keystone-apache-public-access.log" logformat

{% if keystone_enable_tls_backend | bool %}
    SSLEngine on
    SSLCertificateFile /etc/keystone/certs/keystone-cert.pem
    SSLCertificateKeyFile /etc/keystone/certs/keystone-key.pem
{% endif %}

{% if keystone_enable_federation_openid %}
{% if openstack_version != 'yoga' %}
    OIDCXForwardedHeaders "{{ keystone_oidc_forward_header }}"
{% endif %}
    OIDCClaimPrefix "OIDC-"
    OIDCClaimDelimiter ","
    OIDCPKCEMethod S256
    OIDCResponseType "{{ keystone_federation_oidc_response_type }}"
    OIDCScope "{{ keystone_federation_oidc_scopes }}"
#   OIDCMetadataDir {{ keystone_container_federation_oidc_metadata_folder }}
    {# Note: Let's use the Metadata instead of the static metadata files -#}
    OIDCProviderMetadataURL https://{{ keycloak_url }}/realms/{{ keycloak_realm }}/.well-known/openid-configuration
    OIDCSSLValidateServer Off  # the keycloak uses a self-signed cert, so we disable the validation
    OIDCClientID openstack
    OIDCClientSecret {{ keystone_federation_openid_realm_redacted_password }}
{% if keystone_federation_openid_certificate_key_ids | length > 0 %}
    {# Note: OIDCOAuthVerifyCertFiles is a mod_openidc specific param for legacy oauth2 -#}
    OIDCOAuthVerifyCertFiles {{ keystone_federation_openid_certificate_key_ids | join(" ") }}
{% endif %}
    OIDCCryptoPassphrase {{ keystone_federation_openid_crypto_password }}
    OIDCRedirectURI {{ keystone_public_url }}/redirect_uri/
{% if enable_memcached | bool %}
    OIDCCacheType memcache
    OIDCMemCacheServers "{% for host in groups['memcached'] %}{{ 'api' | kolla_address(host) | put_address_in_context('memcache') }}:{{ memcached_port }}{% if not loop.last %} {% endif %}{% endfor %}"
{% endif %}

    <Location ~ "/redirect_uri/">
      Require valid-user
      AuthType openid-connect
    </Location>

    {# WebSSO authentication endpoint -#}
    <Location /v3/auth/OS-FEDERATION/websso/openid>
      Require valid-user
      AuthType openid-connect
    </Location>

{% for idp in keystone_identity_providers %}
{% if idp.protocol == 'openid' %}
    <LocationMatch /v3/auth/OS-FEDERATION/identity_providers/{{ idp.name }}/protocols/{{ idp.protocol }}/websso>
      OIDCDiscoverURL {{ keystone_public_url }}/redirect_uri?iss={{ idp.identifier | urlencode }}
      Require valid-user
      AuthType openid-connect
    </LocationMatch>
{% endif %}
{% endfor %}

{# CLI / API authentication endpoint -#}
{% for idp in keystone_identity_providers %}
{% if idp.protocol == 'openid' %}
    <LocationMatch /v3/OS-FEDERATION/identity_providers/{{ idp.name }}/protocols/{{ idp.protocol }}/auth>
      {# Note: This is the section for oauth2. For some reason the protocol_id needs to be the word "mapped" -#}
      Require valid-user
      {# For AuthType oauth2 see https://github.com/zmartzone/mod_oauth2/blob/master/README.md -#}
      AuthType oauth2
      {# For OIDCUnAuthAction see https://github.com/zmartzone/mod_auth_openidc/blob/master/auth_openidc.conf#L853 -#}
      OIDCUnAuthAction pass
      OAuth2TokenVerify jwks_uri https://{{ keycloak_url }}/realms/{{ keycloak_realm }}/protocol/openid-connect/certs jwks_uri.ssl_verify=false
      {# For OAuth2TargetPass see https://github.com/zmartzone/mod_oauth2/blob/master/oauth2.conf -#}
      OAuth2TargetPass prefix=OIDC-
    </LocationMatch>
{% endif %}
{% endfor %}
{% endif %}
</VirtualHost>

<VirtualHost *:{{ keystone_admin_listen_port }}>
    WSGIDaemonProcess keystone-admin processes={{ openstack_service_workers }} threads=1 user=keystone group=keystone display-name=keystone-admin
    WSGIProcessGroup keystone-admin
    WSGIScriptAlias / {{ binary_path }}/keystone-wsgi-admin
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On
    <IfVersion >= 2.4>
      ErrorLogFormat "%{cu}t %M"
    </IfVersion>
    ErrorLog "{{ keystone_log_dir }}/keystone-apache-admin-error.log"
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b %D \"%{Referer}i\" \"%{User-Agent}i\"" logformat
    CustomLog "{{ keystone_log_dir }}/keystone-apache-admin-access.log" logformat

{% if keystone_enable_tls_backend | bool %}
    SSLEngine on
    SSLCertificateFile /etc/keystone/certs/keystone-cert.pem
    SSLCertificateKeyFile /etc/keystone/certs/keystone-key.pem
{% endif %}
</VirtualHost>
```

I would love some help here. The mapping itself from Keycloak to Keystone works very well.
