### ISSUE TITLE
Ansible-Ceph new openstack_pools|openstack_pools_extra don't Work

### ISSUE THREAD

**Issue by zachelnet** [osism/issues#726]
To define a new pool don't work with the  openstack_pools|openstack_pools_extra variable in "environments/ceph/configuration.yml".

```
openstack_cinder_critical_pool:
  name: "datenkritisch"
  pg_num: "{{ openstack_pool_default_pg_num }}"
  pgp_num: "{{ openstack_pool_default_pg_num }}"
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "4"
  min_size: "{{ openstack_pool_default_min_size }}"
  pg_autoscale_mode: false

openstack_cinder_capacity_pool:
  name: "kapazitaet"
  pg_num: "{{ openstack_pool_default_pg_num }}"
  pgp_num: "{{ openstack_pool_default_pg_num }}"
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size:
  min_size: "{{ openstack_pool_default_min_size }}"
  pg_autoscale_mode: false

openstack_cinder_performance_pool:
  name: "performance"
  pg_num: "{{ openstack_pool_default_pg_num }}"
  pgp_num: "{{ openstack_pool_default_pg_num }}"
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
  size: "2"
  min_size: "{{ openstack_pool_default_min_size }}"
  pg_autoscale_mode: false

openstack_pools_extra:
  - "{{ openstack_cinder_critical_pool }}"
  - "{{ openstack_cinder_capacity_pool }}"
  - "{{ openstack_cinder_performance_pool }}"
```

And in the inventory file of the reconcile I don't found the new pools
