### ISSUE TITLE
gilt.yaml in cfg-generics always points to main branch

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#738]
Hi,

the gilt.yaml file used to overlay changes from cfg-generics repo always points to "main" branch:
https://github.com/osism/cfg-generics/blob/v0.20230919.0/gilt.yml

```
---
- git: https://github.com/osism/cfg-generics.git
  version: main
  files:
```

I would expect to point it to a tag or commit that relates to the current OSISM release in case I want to roll out an older release or roll out the current release at a later point in time.

Kind regards,
André.
