### ISSUE TITLE
"osism apply bootstrap" kills itself

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#757]
Hi,

when I run "osism apply bootstrap" as of (https://osism.github.io/docs/guides/deploy-guide/bootstrap) it kills itself as soon as it comes to the manager and restarts Docker.

The connection to the hosts just gets closed.
A re-run is also not possible. Subsequent calls to "osism apply bootstrap" will just result in

```
/usr/local/bin/osism apply bootstrap -l control3
2023-11-15 08:03:38 | INFO     | No further output after 300 seconds. Therefore finish.

echo $?
0
```

Kind regards,
André.

**Comment by berendt** [comment]
The restart handler for the Docker service:

```
- name: Restart docker service
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: "{{ docker_service_name }}"
  when: (docker_allow_restart|bool and inventory_hostname not in groups[docker_ignore_restart_groupname] | default([])) or
        (docker_allow_restart|bool and inventory_hostname in groups[docker_ignore_restart_groupname] | default([]) and docker_enforce_restart|bool)
```

docker_ignore_restart_groupname is manager by default. This should avoid restarts of the Docker service on manager nodes.

Can you please check whether the restart was executed by the handler on the manager node?
