### ISSUE TITLE
Feature: Let "osism apply reboot" wait synchronously for reboot to be complete 

### ISSUE THREAD

**Issue by nerdicbynature** [osism/issues#758]
Hi,

 "osism apply reboot" just runs in fire-and-forget mode. I would be nice if it waits for a reboot to be complete for automation purposes. For example like this:
```
- name: Reboot nodes
  become: true
  reboot:
    reboot_timeout: 900
    connect_timeout: 5
    post_reboot_delay: 120

```

Kind regards,
André
