### ISSUE TITLE
Remove old architecture-dependent repositories with arch...

### ISSUE THREAD

**Issue by berendt** [osism/issues#849]
After changing the repositories, the old entries remain and must be removed.

```
osism@mgr005:~$ cat /etc/apt/sources.list.d/docker.list
deb [ arch=amd64 ] https://download.docker.com/linux/ubuntu jammy stable
deb https://download.docker.com/linux/ubuntu jammy stable
```

**Comment by berendt** [comment]
Related to https://github.com/osism/issues/issues/841

**Comment by berendt** [comment]
Something like this should remove the old repository in osism.services.docker. Has to be fixed for all roles that add a repository.

```
- name: Remove old architecture-dependent repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [ arch=amd64 ] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: absent
    filename: docker
  when: docker_configure_repository|bool
```
