### ISSUE TITLE
ceph: create-lvm-devices play fails when using disk/by-id/...

### ISSUE THREAD

**Issue by b1knoll** [osism/issues#888]
Hello,

added the disks to the host configuration files like described here:

https://osism.github.io/docs/guides/configuration-guide/ceph#lvm-devices

I used:

disk/by-id/wwn-0x50000...

Running:

osism apply ceph-configure-lvm-volumes

worked fine.

I replaced the previously genereted configuration of the OSDs with the new ones.

All commands worked fine. No errors.

However rolling out the LVMs fails (I masked the UUIDs and server names):

```
osism apply ceph-create-lvm-devices
2024-02-28 22:54:57 | INFO     | Task was prepared for execution. It takes a moment until the task has been started and output is visible here.
[WARNING]: Skipping callback 'ara_default', unable to load due to: The server
dependencies must be installed to record data offline or run the API server.

PLAY [Ceph create LVM devices] *************************************************

TASK [Get extra vars for Ceph configuration] ***********************************
ok: [serverx -> managerx(xxx.xx.xx.xxx)]

TASK [Get block devices present on host] ***************************************
ok: [serverx]

TASK [Create dict of block VGs -> PVs from ceph_osd_devices] *******************
[...]
skipping: [serverx] => (item={'key': 'disk/by-id/wwn-0x50000xxxxxxxxxxx', 'value': {'db_pv': 'disk/by-id/wwn-0x5000yyyyyyyyyyy', 'osd_lvm_uuid': 'zzzzzzzz-aaaa-bbbb-cccc-dddddddddddd'}})
skipping: [serverx]

ASK [Create block VGs] ********************************************************
skipping: [serverx]

TASK [Create block LVs] ********************************************************
skipping: [serverx]

TASK [Create DB VGs] ***********************************************************
fatal: [serverx]: FAILED! =>
  msg: |-
    The conditional check 'block_devices[item.key].holders|length == 0' failed. The error was: error while evaluating conditional (block_devices[item.key].holders|length == 0): 'dict object' has no attribute 'disk/by-id/wwn-0x5000xxxxxxxxxxx'. 'dict object' has no attribute 'disk/by-id/wwn-0x5000xxxxxxxxxxx'                                                                                                                     

    The error appears to be in '/ansible/ceph-create-lvm-devices.yml': line 90, column 11, but may
    be elsewhere in the file depending on the exact syntax problem.
    
    The offending line appears to be:

            
            - name: Create DB VGs
              ^ here

PLAY RECAP *********************************************************************
sbmsi10110                 : ok=2    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
```

**Comment by berendt** [comment]
Please share the relevant part of the host configuration.

**Comment by b1knoll** [comment]
Hi,

alright, I attached a text file with the device configuration in one of the hosts files created by:

osism apply ceph-configure-lvm-volumes

Best,
Marc

[lvm_create_fails.txt](https://github.com/osism/issues/files/14444770/lvm_create_fails.txt)

**Comment by berendt** [comment]
So far I have only tested it with /dev/sdX and /dev/nvmeX. Maybe using disk/by-id is a missing feature (which should definitely be possible).

**Comment by berendt** [comment]
Looks broken. Initial configuration in host vars:

```
ceph_osd_devices:
  disk/by-id/scsi-SQEMU_QEMU_HARDDISK_fc4e381e-eed0-4eee-8bc8-23710a364999:
```

After osism apply ceph-configure-lvm-volumes -l testbed-node-0.testbed.osism.xyz:

```
dragon@testbed-manager:~$ cat /tmp/testbed-node-0.testbed.osism.xyz-ceph-lvm-configuration.yml
---
#
# This is Ceph LVM configuration for testbed-node-0.testbed.osism.xyz
# generated by ceph-configure-lvm-volumes playbook.
#
ceph_osd_devices:
  disk/by-id/scsi-SQEMU_QEMU_HARDDISK_fc4e381e-eed0-4eee-8bc8-23710a364999:
    osd_lvm_uuid: 83a97a55-6c6a-5a62-9e99-fe90b992dced
lvm_volumes: []
```

It should look like this:

```
---
#
# This is Ceph LVM configuration for testbed-node-0.testbed.osism.xyz
# generated by ceph-configure-lvm-volumes playbook.
#
ceph_osd_devices:
  sda:
    osd_lvm_uuid: 5b5d7580-5a99-599e-bd88-ef514e3a4bb1
lvm_volumes:
- data: osd-block-5b5d7580-5a99-599e-bd88-ef514e3a4bb1
  data_vg: ceph-5b5d7580-5a99-599e-bd88-ef514e3a4bb1
```

**Comment by berendt** [comment]
That's the problem:

```
        - name: Get block devices
          ansible.builtin.set_fact:
            block_devices: "{{ hostvars[inventory_hostname].ansible_devices }}"
```

The ansible_devices fact ony includes the sdX, nvmeX, .. names as keys. The other names are provides as a list inside a links dictionary. We have to extend this to be able to also use e.g. scsi-SQEMU_QEMU_HARDDISK_fc4e381e-eed0-4eee-8bc8-23710a364999 as disk name (without disk/by-id).

```
|                                  |                 |   'sdb': { 'holders': [],                                                                                                        |
|                                  |                 |            'host': 'SCSI storage controller: Red Hat, Inc. '                                                                     |
|                                  |                 |                    'Virtio SCSI',                                                                                                |
|                                  |                 |            'links': { 'ids': [ 'scsi-0QEMU_QEMU_HARDDISK_3cb59f5e-3659-45ab-bcca-72d03f87e839',                                  |
|                                  |                 |                                'scsi-SQEMU_QEMU_HARDDISK_3cb59f5e-3659-45ab-bcca-72d03f87e839'],                                 |
|                                  |                 |                       'labels': [],                                                                                              |
|                                  |                 |                       'masters': [],                                                                                             |
|                                  |                 |                       'uuids': []},                                                                                              |
|                                  |                 |            'model': 'QEMU HARDDISK',                                                                                             |
|                                  |                 |            'partitions': {},                                                                                                     |
|                                  |                 |            'removable': '0',                                                                                                     |
|                                  |                 |            'rotational': '1',                                                                                                    |
|                                  |                 |            'sas_address': None,                                                                                                  |
|                                  |                 |            'sas_device_handle': None,                                                                                            |
|                                  |                 |            'scheduler_mode': 'none',                                                                                             |
|                                  |                 |            'sectors': '41943040',                                                                                                |
|                                  |                 |            'sectorsize': '512',                                                                                                  |
|                                  |                 |            'size': '20.00 GB',                                                                                                   |
|                                  |                 |            'support_discard': '4096',                                                                                            |
|                                  |                 |            'vendor': 'QEMU',                                                                                                     |
|                                  |                 |            'virtual': 1},                                                                                                        |
```

**Comment by berendt** [comment]
Configuration after PR:

```
dragon@testbed-manager:~$ cat /tmp/testbed-node-0.testbed.osism.xyz-ceph-lvm-configuration.yml
---
#
# This is Ceph LVM configuration for testbed-node-0.testbed.osism.xyz
# generated by ceph-configure-lvm-volumes playbook.
#
ceph_osd_devices:
  scsi-SQEMU_QEMU_HARDDISK_fc4e381e-eed0-4eee-8bc8-23710a364999:
    osd_lvm_uuid: 959e6a58-2566-5214-aced-be295552ab2c
lvm_volumes:
- data: osd-block-959e6a58-2566-5214-aced-be295552ab2c
  data_vg: ceph-959e6a58-2566-5214-aced-be295552ab2c
```

**Comment by b1knoll** [comment]
Hello,

yes, this still fails.

I changed the configuration using /dev/:

```
ceph_db_devices:
  /dev/sdh:
    num_osds: 3
  /dev/sdi:
    num_osds: 3
[...]

ceph_osd_devices:
  /dev/sdb:
    db_pv: /dev/sdh
  /dev/sdc:
    db_pv: /dev/sdh
[...]

```
But the result is still wrong:

```
ceph_db_devices:
  /dev/sdh:
    num_osds: 3
    vg_name: ceph-db-0c951439-ada4-52e6-b478-decffef2b5f1
  /dev/sdi:
    num_osds: 3
    vg_name: ceph-db-07e4813d-3018-5bf8-8240-fbdabea235a1
[...]
ceph_osd_devices:
  /dev/sdb:
    db_pv: /dev/sdh
    osd_lvm_uuid: 8d3c0544-7298-50e9-86c8-3292528ad0bb
  /dev/sdc:
    db_pv: /dev/sdh
    osd_lvm_uuid: b21f4860-97d2-5962-b6a1-1ed140b144c5
[...]
lvm_volumes: []
```

**Comment by berendt** [comment]
> Hello,
> 
> yes, this still fails.
> 
> I changed the configuration using /dev/:
> 
> ```
> ceph_db_devices:
>   /dev/sdh:
>     num_osds: 3
>   /dev/sdi:
>     num_osds: 3
> [...]
> 
> ceph_osd_devices:
>   /dev/sdb:
>     db_pv: /dev/sdh
>   /dev/sdc:
>     db_pv: /dev/sdh
> [...]
> ```
> 
> But the result is still wrong:
> 
> ```
> ceph_db_devices:
>   /dev/sdh:
>     num_osds: 3
>     vg_name: ceph-db-0c951439-ada4-52e6-b478-decffef2b5f1
>   /dev/sdi:
>     num_osds: 3
>     vg_name: ceph-db-07e4813d-3018-5bf8-8240-fbdabea235a1
> [...]
> ceph_osd_devices:
>   /dev/sdb:
>     db_pv: /dev/sdh
>     osd_lvm_uuid: 8d3c0544-7298-50e9-86c8-3292528ad0bb
>   /dev/sdc:
>     db_pv: /dev/sdh
>     osd_lvm_uuid: b21f4860-97d2-5962-b6a1-1ed140b144c5
> [...]
> lvm_volumes: []
> ```

Try it without the ``/dev/``. Only the name of the device is required.

**Comment by b1knoll** [comment]
I think a temporary solution for me would be a manual edit.

It looks like in standard ceph-ansible:

```
lvm_volumes:
- data: osd-block-5b5d7580-5a99-599e-bd88-ef514e3a4bb1
  data_vg: ceph-5b5d7580-5a99-599e-bd88-ef514e3a4bb1
```

**Comment by b1knoll** [comment]
Alright, i read this: 

> So far I have only tested it with /dev/sdX and /dev/nvmeX. Maybe using disk/by-id is a missing feature (which should definitely be possible).

so I thought it works with /dev/ also.

But yes, it still fails.

This is how my host configuration yaml looks like for the OSDs:

```
ceph_db_devices:
  sdh:
    num_osds: 3
  sdi:
    num_osds: 3
  sdj:
    num_osds: 3
  sdk:
    num_osds: 3
  sdl:
    num_osds: 3
  sdm:
    num_osds: 3

ceph_osd_devices:
  sda:
    db_pv: sdh
  sdb:
    db_pv: sdh
  sdc:
    db_pv: sdh
  sdd:
    db_pv: sdi
  sde:
    db_pv: sdi
  sdf:
    db_pv: sdi
  sdg:
    db_pv: sdj
  sdn:
    db_pv: sdj
  sdo:
    db_pv: sdj
  sdp:
    db_pv: sdk
  sdq:
    db_pv: sdk
  sdr:
    db_pv: sdk
  sds:
    db_pv: sdl
  sdt:
    db_pv: sdl
  sdu:
    db_pv: sdl
  sdv:
    db_pv: sdm
  sdw:
    db_pv: sdm
  sdx:
    db_pv: sdm
```

And the error message after running

osism apply ceph-configure-lvm-volumes

```
TASK [Generate lvm_volumes structure (block + db)] *****************************
fatal: [serverx]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'vg_name'. 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'vg_name'

    The error appears to be in '/ansible/ceph-configure-lvm-volumes.yml': line 241, column 11, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


            - name: Generate lvm_volumes structure (block + db)
              ^ here

PLAY RECAP *********************************************************************
serverx                 : ok=5    changed=0    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
```

Is my host configuration syntax wrong somehow?

**Comment by berendt** [comment]
I have now tested and fixed all possible scenarios in the configure play. Unfortunately, there were several sloppy and copy & paste errors from the previous creator of the plays.

It's now also possible to use disk/by-id. This way:

```
ceph_osd_devices:
  disk/by-id/scsi-0QEMU_QEMU_HARDDISK_fc4e381e-eed0-4eee-8bc8-23710a364999:
```

I'll test the create play tomorrow.

**Comment by b1knoll** [comment]
Hello,

thank you.

Yes, the configuration is working now. I tried it with the simple sda:, etc. notations.

I tested it with the create script and this first failed, because I did not add db_size: to the ceph_deb_devices:.

It calculated a wrong size for the DBs.

Now it fails because I did not define  db_wal_db_lv_sizes.

No, I didnt. I just added db_size.

I did not want to use ceph_wal_devices: or ceph_db_wal_devices:.

Do I have to use it?

I also missed ceph_osd_db_wal_devices_buffer_space_percent: 10.
[host_osd_configuration.txt](https://github.com/osism/issues/files/14459539/host_osd_configuration.txt)

Have a look at my configuration and the error message:

```
TASK [Create DB LVs for ceph_db_wal_devices] ***********************************
fatal: [serverx]: FAILED! =>
  msg: |-
    The conditional check 'item.db_vg in db_wal_db_lv_sizes' failed. The error was: error while evaluating conditional (item.db_vg in db_wal_db_lv_sizes): 'db_wal_db_lv_sizes' is undefined. 'db_wal_db_lv_sizes' is undefined

    The error appears to be in '/ansible/ceph-create-lvm-devices.yml': line 656, column 11, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

            # Create DB LVs for ceph_db_wal_devices
            - name: Create DB LVs for ceph_db_wal_devices
              ^ here

PLAY RECAP *********************************************************************
serverx                 : ok=81   changed=4    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0
```

**Comment by b1knoll** [comment]
Adding:

ceph_osd_db_wal_devices_buffer_space_percent: 10

ceph_wal_devices: []

ceph_db_wal_devices: []

to the host configuration worked for:

osism apply ceph-configure-lvm-volumes

**Comment by b1knoll** [comment]
Tryed adding ceph_db_wal_devices: with 0 GB for the wal.

Everything fails now. I am out of ideas:

osism reconciler sync
2024-03-01 11:53:41 | INFO     | Task d153d971-f23a-4cd1-945a-cc660c504b95 is running in background. Output coming soon.
2024-03-01 11:53:43 | INFO     | Writing 050-kolla-ceph-rgw-hosts.yml with ceph_rgw_hosts
2024-03-01 11:53:43 | INFO     | Writing 050-infrastructure-cephclient-mons.yml with cephclient_mons
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  mapping values are not allowed in this context

The error appears to be in '/inventory.pre/host_vars/sbmsi10110.yml': line 114, column 14, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    num_osds: 3
      db_size: 1150 GB
             ^ here

**Comment by berendt** [comment]
I haven't finished my revision of the plays yet. I think it makes more sense to continue testing on Monday.

**Comment by berendt** [comment]
> I haven't finished my revision of the plays yet. I think it makes more sense to continue testing on Monday.

* documentation revisited, explained the different scenarios in more detail & fixed a YAML syntax issue in the examples
* reverted a PR that made the generated configuration unusable

This should generate the configuration in your case:

```
ceph_db_devices:
  sdh:
    num_osds: 3
    db_size: 1150 GB
  sdi:
    num_osds: 3
    db_size: 1150 GB
  sdj:
    num_osds: 3
    db_size: 1150 GB
  sdk:
    num_osds: 3
    db_size: 1150 GB
  sdl:
    num_osds: 3
    db_size: 1150 GB
  sdm:
    num_osds: 3
    db_size: 1150 GB

ceph_osd_devices:
  sda:
    db_pv: sdh
  sdb:
    db_pv: sdh
  sdc:
    db_pv: sdh
  sdd:
    db_pv: sdi
  sde:
    db_pv: sdi
  sdf:
    db_pv: sdi
  sdg:
    db_pv: sdj
  sdn:
    db_pv: sdj
  sdo:
    db_pv: sdj
  sdp:
    db_pv: sdk
  sdq:
    db_pv: sdk
  sdr:
    db_pv: sdk
  sds:
    db_pv: sdl
  sdt:
    db_pv: sdl
  sdu:
    db_pv: sdl
  sdv:
    db_pv: sdm
  sdw:
    db_pv: sdm
  sdx:
    db_pv: sdm
```
