### ISSUE TITLE
Update galaxy meta information

### ISSUE THREAD

**Issue by berendt** [osism/issues#982]
The the meta/main.yml files in the Ansible collections & playbooks we have not up-to-date versions & distributions at the moment:

```
  min_ansible_version: 2.10.0
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy     
```

Update the platforms and min Ansible version in all Ansible collections & playbooks repositories.

Platforms: Ubuntu Jammy, Debian Bookworm, CentOS Stream
Min Ansible Version: 2.16.0
